/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import com.docspring.CombinedSubmissionAction;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CombinedSubmission
 */
public class CombinedSubmissionTest {
    private final CombinedSubmission model = new CombinedSubmission();

    /**
     * Model tests for CombinedSubmission
     */
    @Test
    public void testCombinedSubmission() {
        // TODO: test CombinedSubmission
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'expired'
     */
    @Test
    public void expiredTest() {
        // TODO: test expired
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'processedAt'
     */
    @Test
    public void processedAtTest() {
        // TODO: test processedAt
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'submissionIds'
     */
    @Test
    public void submissionIdsTest() {
        // TODO: test submissionIds
    }

    /**
     * Test the property 'sourcePdfs'
     */
    @Test
    public void sourcePdfsTest() {
        // TODO: test sourcePdfs
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'pdfHash'
     */
    @Test
    public void pdfHashTest() {
        // TODO: test pdfHash
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

}
