/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubmissionDataRequestEvent
 */
public class SubmissionDataRequestEventTest {
    private final SubmissionDataRequestEvent model = new SubmissionDataRequestEvent();

    /**
     * Model tests for SubmissionDataRequestEvent
     */
    @Test
    public void testSubmissionDataRequestEvent() {
        // TODO: test SubmissionDataRequestEvent
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'submissionId'
     */
    @Test
    public void submissionIdTest() {
        // TODO: test submissionId
    }

    /**
     * Test the property 'submissionDataRequestId'
     */
    @Test
    public void submissionDataRequestIdTest() {
        // TODO: test submissionDataRequestId
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'messageType'
     */
    @Test
    public void messageTypeTest() {
        // TODO: test messageType
    }

    /**
     * Test the property 'messageRecipient'
     */
    @Test
    public void messageRecipientTest() {
        // TODO: test messageRecipient
    }

    /**
     * Test the property 'occurredAt'
     */
    @Test
    public void occurredAtTest() {
        // TODO: test occurredAt
    }

}
