/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubmissionAction
 */
public class SubmissionActionTest {
    private final SubmissionAction model = new SubmissionAction();

    /**
     * Model tests for SubmissionAction
     */
    @Test
    public void testSubmissionAction() {
        // TODO: test SubmissionAction
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'integrationId'
     */
    @Test
    public void integrationIdTest() {
        // TODO: test integrationId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'actionType'
     */
    @Test
    public void actionTypeTest() {
        // TODO: test actionType
    }

    /**
     * Test the property 'actionCategory'
     */
    @Test
    public void actionCategoryTest() {
        // TODO: test actionCategory
    }

    /**
     * Test the property 'resultData'
     */
    @Test
    public void resultDataTest() {
        // TODO: test resultData
    }

}
