/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AddFieldsTemplateResponse
 */
@javax.annotation.Generated(value = "com.docspring.codegen.DocSpringJavaClientCodegen", date = "2020-09-24T00:45:30.265+08:00[Asia/Kuala_Lumpur]")
public class AddFieldsTemplateResponse {
  public static final String SERIALIZED_NAME_NEW_FIELD_IDS = "new_field_ids";
  @SerializedName(SERIALIZED_NAME_NEW_FIELD_IDS)
  private List<Integer> newFieldIds = null;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<String> errors = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    SUCCESS("success"),
    
    ERROR("error");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status = null;

  public AddFieldsTemplateResponse newFieldIds(List<Integer> newFieldIds) {
    this.newFieldIds = newFieldIds;
    return this;
  }

  public AddFieldsTemplateResponse addNewFieldIdsItem(Integer newFieldIdsItem) {
    if (this.newFieldIds == null) {
      this.newFieldIds = new ArrayList<Integer>();
    }
    this.newFieldIds.add(newFieldIdsItem);
    return this;
  }

   /**
   * Get newFieldIds
   * @return newFieldIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getNewFieldIds() {
    return newFieldIds;
  }

  public void setNewFieldIds(List<Integer> newFieldIds) {
    this.newFieldIds = newFieldIds;
  }

  public AddFieldsTemplateResponse errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public AddFieldsTemplateResponse addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public AddFieldsTemplateResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddFieldsTemplateResponse addFieldsTemplateResponse = (AddFieldsTemplateResponse) o;
    return Objects.equals(this.newFieldIds, addFieldsTemplateResponse.newFieldIds) &&
        Objects.equals(this.errors, addFieldsTemplateResponse.errors) &&
        Objects.equals(this.status, addFieldsTemplateResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newFieldIds, errors, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddFieldsTemplateResponse {\n");
    
    sb.append("    newFieldIds: ").append(toIndentedString(newFieldIds)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

