/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docspring.SubmissionBatch;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * BatchGeneratePdfs201Response
 */
@JsonPropertyOrder({
  BatchGeneratePdfs201Response.JSON_PROPERTY_STATUS,
  BatchGeneratePdfs201Response.JSON_PROPERTY_ERROR,
  BatchGeneratePdfs201Response.JSON_PROPERTY_ERRORS,
  BatchGeneratePdfs201Response.JSON_PROPERTY_SUBMISSION_BATCH,
  BatchGeneratePdfs201Response.JSON_PROPERTY_SUBMISSIONS
})
@JsonTypeName("batchGeneratePdfs_201_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class BatchGeneratePdfs201Response {
  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    SUCCESS(String.valueOf("success")),
    
    ERROR(String.valueOf("error"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private String error;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nullable
  private List<String> errors = new ArrayList<>();

  public static final String JSON_PROPERTY_SUBMISSION_BATCH = "submission_batch";
  @javax.annotation.Nonnull
  private SubmissionBatch submissionBatch;

  public static final String JSON_PROPERTY_SUBMISSIONS = "submissions";
  @javax.annotation.Nonnull
  private List<Object> submissions = new ArrayList<>();

  public BatchGeneratePdfs201Response() { 
  }

  public BatchGeneratePdfs201Response status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public BatchGeneratePdfs201Response error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public BatchGeneratePdfs201Response errors(@javax.annotation.Nullable List<String> errors) {
    this.errors = errors;
    return this;
  }

  public BatchGeneratePdfs201Response addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getErrors() {
    return errors;
  }


  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@javax.annotation.Nullable List<String> errors) {
    this.errors = errors;
  }


  public BatchGeneratePdfs201Response submissionBatch(@javax.annotation.Nonnull SubmissionBatch submissionBatch) {
    this.submissionBatch = submissionBatch;
    return this;
  }

  /**
   * Get submissionBatch
   * @return submissionBatch
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBMISSION_BATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SubmissionBatch getSubmissionBatch() {
    return submissionBatch;
  }


  @JsonProperty(JSON_PROPERTY_SUBMISSION_BATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubmissionBatch(@javax.annotation.Nonnull SubmissionBatch submissionBatch) {
    this.submissionBatch = submissionBatch;
  }


  public BatchGeneratePdfs201Response submissions(@javax.annotation.Nonnull List<Object> submissions) {
    this.submissions = submissions;
    return this;
  }

  public BatchGeneratePdfs201Response addSubmissionsItem(Object submissionsItem) {
    if (this.submissions == null) {
      this.submissions = new ArrayList<>();
    }
    this.submissions.add(submissionsItem);
    return this;
  }

  /**
   * Get submissions
   * @return submissions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBMISSIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Object> getSubmissions() {
    return submissions;
  }


  @JsonProperty(JSON_PROPERTY_SUBMISSIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubmissions(@javax.annotation.Nonnull List<Object> submissions) {
    this.submissions = submissions;
  }


  /**
   * Return true if this batchGeneratePdfs_201_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchGeneratePdfs201Response batchGeneratePdfs201Response = (BatchGeneratePdfs201Response) o;
    return Objects.equals(this.status, batchGeneratePdfs201Response.status) &&
        Objects.equals(this.error, batchGeneratePdfs201Response.error) &&
        Objects.equals(this.errors, batchGeneratePdfs201Response.errors) &&
        Objects.equals(this.submissionBatch, batchGeneratePdfs201Response.submissionBatch) &&
        Objects.equals(this.submissions, batchGeneratePdfs201Response.submissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, error, errors, submissionBatch, submissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchGeneratePdfs201Response {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    submissionBatch: ").append(toIndentedString(submissionBatch)).append("\n");
    sb.append("    submissions: ").append(toIndentedString(submissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

