/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * CombinedSubmissionData
 */
@JsonPropertyOrder({
  CombinedSubmissionData.JSON_PROPERTY_EXPIRES_IN,
  CombinedSubmissionData.JSON_PROPERTY_METADATA,
  CombinedSubmissionData.JSON_PROPERTY_PASSWORD,
  CombinedSubmissionData.JSON_PROPERTY_SUBMISSION_IDS,
  CombinedSubmissionData.JSON_PROPERTY_TEST
})
@JsonTypeName("combined_submission_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CombinedSubmissionData {
  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @javax.annotation.Nullable
  private Integer expiresIn;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_SUBMISSION_IDS = "submission_ids";
  @javax.annotation.Nonnull
  private List<String> submissionIds = new ArrayList<>();

  public static final String JSON_PROPERTY_TEST = "test";
  @javax.annotation.Nullable
  private Boolean test;

  public CombinedSubmissionData() { 
  }

  public CombinedSubmissionData expiresIn(@javax.annotation.Nullable Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Get expiresIn
   * @return expiresIn
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresIn(@javax.annotation.Nullable Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  public CombinedSubmissionData metadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }


  public CombinedSubmissionData password(@javax.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }


  public CombinedSubmissionData submissionIds(@javax.annotation.Nonnull List<String> submissionIds) {
    this.submissionIds = submissionIds;
    return this;
  }

  public CombinedSubmissionData addSubmissionIdsItem(String submissionIdsItem) {
    if (this.submissionIds == null) {
      this.submissionIds = new ArrayList<>();
    }
    this.submissionIds.add(submissionIdsItem);
    return this;
  }

  /**
   * Get submissionIds
   * @return submissionIds
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBMISSION_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getSubmissionIds() {
    return submissionIds;
  }


  @JsonProperty(JSON_PROPERTY_SUBMISSION_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubmissionIds(@javax.annotation.Nonnull List<String> submissionIds) {
    this.submissionIds = submissionIds;
  }


  public CombinedSubmissionData test(@javax.annotation.Nullable Boolean test) {
    this.test = test;
    return this;
  }

  /**
   * Get test
   * @return test
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTest() {
    return test;
  }


  @JsonProperty(JSON_PROPERTY_TEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTest(@javax.annotation.Nullable Boolean test) {
    this.test = test;
  }


  /**
   * Return true if this combined_submission_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CombinedSubmissionData combinedSubmissionData = (CombinedSubmissionData) o;
    return Objects.equals(this.expiresIn, combinedSubmissionData.expiresIn) &&
        Objects.equals(this.metadata, combinedSubmissionData.metadata) &&
        Objects.equals(this.password, combinedSubmissionData.password) &&
        Objects.equals(this.submissionIds, combinedSubmissionData.submissionIds) &&
        Objects.equals(this.test, combinedSubmissionData.test);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresIn, metadata, password, submissionIds, test);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CombinedSubmissionData {\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    submissionIds: ").append(toIndentedString(submissionIds)).append("\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

