/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docspring.CreateSubmissionDataRequestData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * CreatePdfSubmissionData
 */
@JsonPropertyOrder({
  CreatePdfSubmissionData.JSON_PROPERTY_DATA,
  CreatePdfSubmissionData.JSON_PROPERTY_DATA_REQUESTS,
  CreatePdfSubmissionData.JSON_PROPERTY_EDITABLE,
  CreatePdfSubmissionData.JSON_PROPERTY_EXPIRES_IN,
  CreatePdfSubmissionData.JSON_PROPERTY_FIELD_OVERRIDES,
  CreatePdfSubmissionData.JSON_PROPERTY_METADATA,
  CreatePdfSubmissionData.JSON_PROPERTY_PASSWORD,
  CreatePdfSubmissionData.JSON_PROPERTY_TEST,
  CreatePdfSubmissionData.JSON_PROPERTY_VERSION
})
@JsonTypeName("create_pdf_submission_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CreatePdfSubmissionData {
  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private Object data;

  public static final String JSON_PROPERTY_DATA_REQUESTS = "data_requests";
  @javax.annotation.Nullable
  private List<CreateSubmissionDataRequestData> dataRequests = new ArrayList<>();

  public static final String JSON_PROPERTY_EDITABLE = "editable";
  @javax.annotation.Nullable
  private Boolean editable;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @javax.annotation.Nullable
  private Integer expiresIn;

  public static final String JSON_PROPERTY_FIELD_OVERRIDES = "field_overrides";
  @javax.annotation.Nullable
  private Object fieldOverrides;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_TEST = "test";
  @javax.annotation.Nullable
  private Boolean test;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private String version;

  public CreatePdfSubmissionData() { 
  }

  public CreatePdfSubmissionData data(@javax.annotation.Nonnull Object data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull Object data) {
    this.data = data;
  }


  public CreatePdfSubmissionData dataRequests(@javax.annotation.Nullable List<CreateSubmissionDataRequestData> dataRequests) {
    this.dataRequests = dataRequests;
    return this;
  }

  public CreatePdfSubmissionData addDataRequestsItem(CreateSubmissionDataRequestData dataRequestsItem) {
    if (this.dataRequests == null) {
      this.dataRequests = new ArrayList<>();
    }
    this.dataRequests.add(dataRequestsItem);
    return this;
  }

  /**
   * Get dataRequests
   * @return dataRequests
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CreateSubmissionDataRequestData> getDataRequests() {
    return dataRequests;
  }


  @JsonProperty(JSON_PROPERTY_DATA_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataRequests(@javax.annotation.Nullable List<CreateSubmissionDataRequestData> dataRequests) {
    this.dataRequests = dataRequests;
  }


  public CreatePdfSubmissionData editable(@javax.annotation.Nullable Boolean editable) {
    this.editable = editable;
    return this;
  }

  /**
   * Get editable
   * @return editable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEditable() {
    return editable;
  }


  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditable(@javax.annotation.Nullable Boolean editable) {
    this.editable = editable;
  }


  public CreatePdfSubmissionData expiresIn(@javax.annotation.Nullable Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Get expiresIn
   * @return expiresIn
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresIn(@javax.annotation.Nullable Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  public CreatePdfSubmissionData fieldOverrides(@javax.annotation.Nullable Object fieldOverrides) {
    this.fieldOverrides = fieldOverrides;
    return this;
  }

  /**
   * Get fieldOverrides
   * @return fieldOverrides
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_OVERRIDES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getFieldOverrides() {
    return fieldOverrides;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_OVERRIDES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldOverrides(@javax.annotation.Nullable Object fieldOverrides) {
    this.fieldOverrides = fieldOverrides;
  }


  public CreatePdfSubmissionData metadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }


  public CreatePdfSubmissionData password(@javax.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }


  public CreatePdfSubmissionData test(@javax.annotation.Nullable Boolean test) {
    this.test = test;
    return this;
  }

  /**
   * Get test
   * @return test
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTest() {
    return test;
  }


  @JsonProperty(JSON_PROPERTY_TEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTest(@javax.annotation.Nullable Boolean test) {
    this.test = test;
  }


  public CreatePdfSubmissionData version(@javax.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable String version) {
    this.version = version;
  }


  /**
   * Return true if this create_pdf_submission_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePdfSubmissionData createPdfSubmissionData = (CreatePdfSubmissionData) o;
    return Objects.equals(this.data, createPdfSubmissionData.data) &&
        Objects.equals(this.dataRequests, createPdfSubmissionData.dataRequests) &&
        Objects.equals(this.editable, createPdfSubmissionData.editable) &&
        Objects.equals(this.expiresIn, createPdfSubmissionData.expiresIn) &&
        Objects.equals(this.fieldOverrides, createPdfSubmissionData.fieldOverrides) &&
        Objects.equals(this.metadata, createPdfSubmissionData.metadata) &&
        Objects.equals(this.password, createPdfSubmissionData.password) &&
        Objects.equals(this.test, createPdfSubmissionData.test) &&
        Objects.equals(this.version, createPdfSubmissionData.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, dataRequests, editable, expiresIn, fieldOverrides, metadata, password, test, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePdfSubmissionData {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    dataRequests: ").append(toIndentedString(dataRequests)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    fieldOverrides: ").append(toIndentedString(fieldOverrides)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

