/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * CreateCustomFileData
 */
@JsonPropertyOrder({
  CreateCustomFileData.JSON_PROPERTY_CACHE_ID
})
@JsonTypeName("create_custom_file_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CreateCustomFileData {
  public static final String JSON_PROPERTY_CACHE_ID = "cache_id";
  @javax.annotation.Nonnull
  private String cacheId;

  public CreateCustomFileData() { 
  }

  public CreateCustomFileData cacheId(@javax.annotation.Nonnull String cacheId) {
    this.cacheId = cacheId;
    return this;
  }

  /**
   * Get cacheId
   * @return cacheId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CACHE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCacheId() {
    return cacheId;
  }


  @JsonProperty(JSON_PROPERTY_CACHE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCacheId(@javax.annotation.Nonnull String cacheId) {
    this.cacheId = cacheId;
  }


  /**
   * Return true if this create_custom_file_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCustomFileData createCustomFileData = (CreateCustomFileData) o;
    return Objects.equals(this.cacheId, createCustomFileData.cacheId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cacheId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCustomFileData {\n");
    sb.append("    cacheId: ").append(toIndentedString(cacheId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

