/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docspring.SubmissionAction;
import com.docspring.SubmissionDataRequest;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * SubmissionPreview
 */
@JsonPropertyOrder({
  SubmissionPreview.JSON_PROPERTY_BATCH_ID,
  SubmissionPreview.JSON_PROPERTY_DATA_REQUESTS,
  SubmissionPreview.JSON_PROPERTY_EDITABLE,
  SubmissionPreview.JSON_PROPERTY_EXPIRED,
  SubmissionPreview.JSON_PROPERTY_EXPIRES_AT,
  SubmissionPreview.JSON_PROPERTY_ID,
  SubmissionPreview.JSON_PROPERTY_JSON_SCHEMA_ERRORS,
  SubmissionPreview.JSON_PROPERTY_METADATA,
  SubmissionPreview.JSON_PROPERTY_PASSWORD,
  SubmissionPreview.JSON_PROPERTY_PROCESSED_AT,
  SubmissionPreview.JSON_PROPERTY_STATE,
  SubmissionPreview.JSON_PROPERTY_TEMPLATE_ID,
  SubmissionPreview.JSON_PROPERTY_TEST,
  SubmissionPreview.JSON_PROPERTY_TRUNCATED_TEXT,
  SubmissionPreview.JSON_PROPERTY_PDF_HASH,
  SubmissionPreview.JSON_PROPERTY_DOWNLOAD_URL,
  SubmissionPreview.JSON_PROPERTY_PERMANENT_DOWNLOAD_URL,
  SubmissionPreview.JSON_PROPERTY_PREVIEW_DOWNLOAD_URL,
  SubmissionPreview.JSON_PROPERTY_PREVIEW_GENERATED_AT,
  SubmissionPreview.JSON_PROPERTY_AUDIT_TRAIL_DOWNLOAD_URL,
  SubmissionPreview.JSON_PROPERTY_ACTIONS
})
@JsonTypeName("submission_preview")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SubmissionPreview {
  public static final String JSON_PROPERTY_BATCH_ID = "batch_id";
  @javax.annotation.Nullable
  private String batchId;

  public static final String JSON_PROPERTY_DATA_REQUESTS = "data_requests";
  @javax.annotation.Nonnull
  private List<SubmissionDataRequest> dataRequests = new ArrayList<>();

  public static final String JSON_PROPERTY_EDITABLE = "editable";
  @javax.annotation.Nullable
  private Boolean editable;

  public static final String JSON_PROPERTY_EXPIRED = "expired";
  @javax.annotation.Nonnull
  private Boolean expired;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @javax.annotation.Nullable
  private String expiresAt;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_JSON_SCHEMA_ERRORS = "json_schema_errors";
  @javax.annotation.Nullable
  private List<String> jsonSchemaErrors;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nonnull
  private Object metadata;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_PROCESSED_AT = "processed_at";
  @javax.annotation.Nullable
  private String processedAt;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    PENDING(String.valueOf("pending")),
    
    PROCESSED(String.valueOf("processed")),
    
    INVALID_DATA(String.valueOf("invalid_data")),
    
    ERROR(String.valueOf("error")),
    
    IMAGE_DOWNLOAD_FAILED(String.valueOf("image_download_failed")),
    
    IMAGE_PROCESSING_FAILED(String.valueOf("image_processing_failed")),
    
    WAITING_FOR_DATA_REQUESTS(String.valueOf("waiting_for_data_requests")),
    
    SYNTAX_ERROR(String.valueOf("syntax_error")),
    
    ACCOUNT_SUSPENDED(String.valueOf("account_suspended")),
    
    LICENSE_REVOKED(String.valueOf("license_revoked")),
    
    ACCIDENTAL(String.valueOf("accidental"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nonnull
  private StateEnum state;

  public static final String JSON_PROPERTY_TEMPLATE_ID = "template_id";
  @javax.annotation.Nullable
  private String templateId;

  public static final String JSON_PROPERTY_TEST = "test";
  @javax.annotation.Nonnull
  private Boolean test;

  public static final String JSON_PROPERTY_TRUNCATED_TEXT = "truncated_text";
  @javax.annotation.Nullable
  private Object truncatedText;

  public static final String JSON_PROPERTY_PDF_HASH = "pdf_hash";
  @javax.annotation.Nullable
  private String pdfHash;

  public static final String JSON_PROPERTY_DOWNLOAD_URL = "download_url";
  @javax.annotation.Nullable
  private String downloadUrl;

  public static final String JSON_PROPERTY_PERMANENT_DOWNLOAD_URL = "permanent_download_url";
  @javax.annotation.Nullable
  private String permanentDownloadUrl;

  public static final String JSON_PROPERTY_PREVIEW_DOWNLOAD_URL = "preview_download_url";
  @javax.annotation.Nullable
  private String previewDownloadUrl;

  public static final String JSON_PROPERTY_PREVIEW_GENERATED_AT = "preview_generated_at";
  @javax.annotation.Nullable
  private String previewGeneratedAt;

  public static final String JSON_PROPERTY_AUDIT_TRAIL_DOWNLOAD_URL = "audit_trail_download_url";
  @javax.annotation.Nullable
  private String auditTrailDownloadUrl;

  public static final String JSON_PROPERTY_ACTIONS = "actions";
  @javax.annotation.Nonnull
  private List<SubmissionAction> actions = new ArrayList<>();

  public SubmissionPreview() { 
  }

  public SubmissionPreview batchId(@javax.annotation.Nullable String batchId) {
    this.batchId = batchId;
    return this;
  }

  /**
   * Get batchId
   * @return batchId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBatchId() {
    return batchId;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBatchId(@javax.annotation.Nullable String batchId) {
    this.batchId = batchId;
  }


  public SubmissionPreview dataRequests(@javax.annotation.Nonnull List<SubmissionDataRequest> dataRequests) {
    this.dataRequests = dataRequests;
    return this;
  }

  public SubmissionPreview addDataRequestsItem(SubmissionDataRequest dataRequestsItem) {
    if (this.dataRequests == null) {
      this.dataRequests = new ArrayList<>();
    }
    this.dataRequests.add(dataRequestsItem);
    return this;
  }

  /**
   * Get dataRequests
   * @return dataRequests
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SubmissionDataRequest> getDataRequests() {
    return dataRequests;
  }


  @JsonProperty(JSON_PROPERTY_DATA_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataRequests(@javax.annotation.Nonnull List<SubmissionDataRequest> dataRequests) {
    this.dataRequests = dataRequests;
  }


  public SubmissionPreview editable(@javax.annotation.Nullable Boolean editable) {
    this.editable = editable;
    return this;
  }

  /**
   * Get editable
   * @return editable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getEditable() {
    return editable;
  }


  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEditable(@javax.annotation.Nullable Boolean editable) {
    this.editable = editable;
  }


  public SubmissionPreview expired(@javax.annotation.Nonnull Boolean expired) {
    this.expired = expired;
    return this;
  }

  /**
   * Get expired
   * @return expired
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getExpired() {
    return expired;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpired(@javax.annotation.Nonnull Boolean expired) {
    this.expired = expired;
  }


  public SubmissionPreview expiresAt(@javax.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresAt(@javax.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public SubmissionPreview id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public SubmissionPreview jsonSchemaErrors(@javax.annotation.Nullable List<String> jsonSchemaErrors) {
    this.jsonSchemaErrors = jsonSchemaErrors;
    return this;
  }

  public SubmissionPreview addJsonSchemaErrorsItem(String jsonSchemaErrorsItem) {
    if (this.jsonSchemaErrors == null) {
      this.jsonSchemaErrors = new ArrayList<>();
    }
    this.jsonSchemaErrors.add(jsonSchemaErrorsItem);
    return this;
  }

  /**
   * Get jsonSchemaErrors
   * @return jsonSchemaErrors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JSON_SCHEMA_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getJsonSchemaErrors() {
    return jsonSchemaErrors;
  }


  @JsonProperty(JSON_PROPERTY_JSON_SCHEMA_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJsonSchemaErrors(@javax.annotation.Nullable List<String> jsonSchemaErrors) {
    this.jsonSchemaErrors = jsonSchemaErrors;
  }


  public SubmissionPreview metadata(@javax.annotation.Nonnull Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@javax.annotation.Nonnull Object metadata) {
    this.metadata = metadata;
  }


  public SubmissionPreview password(@javax.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }


  public SubmissionPreview processedAt(@javax.annotation.Nullable String processedAt) {
    this.processedAt = processedAt;
    return this;
  }

  /**
   * Get processedAt
   * @return processedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessedAt() {
    return processedAt;
  }


  @JsonProperty(JSON_PROPERTY_PROCESSED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProcessedAt(@javax.annotation.Nullable String processedAt) {
    this.processedAt = processedAt;
  }


  public SubmissionPreview state(@javax.annotation.Nonnull StateEnum state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@javax.annotation.Nonnull StateEnum state) {
    this.state = state;
  }


  public SubmissionPreview templateId(@javax.annotation.Nullable String templateId) {
    this.templateId = templateId;
    return this;
  }

  /**
   * Get templateId
   * @return templateId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPLATE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTemplateId() {
    return templateId;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplateId(@javax.annotation.Nullable String templateId) {
    this.templateId = templateId;
  }


  public SubmissionPreview test(@javax.annotation.Nonnull Boolean test) {
    this.test = test;
    return this;
  }

  /**
   * Get test
   * @return test
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTest() {
    return test;
  }


  @JsonProperty(JSON_PROPERTY_TEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTest(@javax.annotation.Nonnull Boolean test) {
    this.test = test;
  }


  public SubmissionPreview truncatedText(@javax.annotation.Nullable Object truncatedText) {
    this.truncatedText = truncatedText;
    return this;
  }

  /**
   * Get truncatedText
   * @return truncatedText
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRUNCATED_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getTruncatedText() {
    return truncatedText;
  }


  @JsonProperty(JSON_PROPERTY_TRUNCATED_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTruncatedText(@javax.annotation.Nullable Object truncatedText) {
    this.truncatedText = truncatedText;
  }


  public SubmissionPreview pdfHash(@javax.annotation.Nullable String pdfHash) {
    this.pdfHash = pdfHash;
    return this;
  }

  /**
   * Get pdfHash
   * @return pdfHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PDF_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPdfHash() {
    return pdfHash;
  }


  @JsonProperty(JSON_PROPERTY_PDF_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPdfHash(@javax.annotation.Nullable String pdfHash) {
    this.pdfHash = pdfHash;
  }


  public SubmissionPreview downloadUrl(@javax.annotation.Nullable String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

  /**
   * Get downloadUrl
   * @return downloadUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDownloadUrl() {
    return downloadUrl;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDownloadUrl(@javax.annotation.Nullable String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }


  public SubmissionPreview permanentDownloadUrl(@javax.annotation.Nullable String permanentDownloadUrl) {
    this.permanentDownloadUrl = permanentDownloadUrl;
    return this;
  }

  /**
   * Get permanentDownloadUrl
   * @return permanentDownloadUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMANENT_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPermanentDownloadUrl() {
    return permanentDownloadUrl;
  }


  @JsonProperty(JSON_PROPERTY_PERMANENT_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermanentDownloadUrl(@javax.annotation.Nullable String permanentDownloadUrl) {
    this.permanentDownloadUrl = permanentDownloadUrl;
  }


  public SubmissionPreview previewDownloadUrl(@javax.annotation.Nullable String previewDownloadUrl) {
    this.previewDownloadUrl = previewDownloadUrl;
    return this;
  }

  /**
   * Get previewDownloadUrl
   * @return previewDownloadUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREVIEW_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPreviewDownloadUrl() {
    return previewDownloadUrl;
  }


  @JsonProperty(JSON_PROPERTY_PREVIEW_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreviewDownloadUrl(@javax.annotation.Nullable String previewDownloadUrl) {
    this.previewDownloadUrl = previewDownloadUrl;
  }


  public SubmissionPreview previewGeneratedAt(@javax.annotation.Nullable String previewGeneratedAt) {
    this.previewGeneratedAt = previewGeneratedAt;
    return this;
  }

  /**
   * Get previewGeneratedAt
   * @return previewGeneratedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREVIEW_GENERATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPreviewGeneratedAt() {
    return previewGeneratedAt;
  }


  @JsonProperty(JSON_PROPERTY_PREVIEW_GENERATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreviewGeneratedAt(@javax.annotation.Nullable String previewGeneratedAt) {
    this.previewGeneratedAt = previewGeneratedAt;
  }


  public SubmissionPreview auditTrailDownloadUrl(@javax.annotation.Nullable String auditTrailDownloadUrl) {
    this.auditTrailDownloadUrl = auditTrailDownloadUrl;
    return this;
  }

  /**
   * Get auditTrailDownloadUrl
   * @return auditTrailDownloadUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDIT_TRAIL_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuditTrailDownloadUrl() {
    return auditTrailDownloadUrl;
  }


  @JsonProperty(JSON_PROPERTY_AUDIT_TRAIL_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuditTrailDownloadUrl(@javax.annotation.Nullable String auditTrailDownloadUrl) {
    this.auditTrailDownloadUrl = auditTrailDownloadUrl;
  }


  public SubmissionPreview actions(@javax.annotation.Nonnull List<SubmissionAction> actions) {
    this.actions = actions;
    return this;
  }

  public SubmissionPreview addActionsItem(SubmissionAction actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

  /**
   * Get actions
   * @return actions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SubmissionAction> getActions() {
    return actions;
  }


  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActions(@javax.annotation.Nonnull List<SubmissionAction> actions) {
    this.actions = actions;
  }


  /**
   * Return true if this submission_preview object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmissionPreview submissionPreview = (SubmissionPreview) o;
    return Objects.equals(this.batchId, submissionPreview.batchId) &&
        Objects.equals(this.dataRequests, submissionPreview.dataRequests) &&
        Objects.equals(this.editable, submissionPreview.editable) &&
        Objects.equals(this.expired, submissionPreview.expired) &&
        Objects.equals(this.expiresAt, submissionPreview.expiresAt) &&
        Objects.equals(this.id, submissionPreview.id) &&
        Objects.equals(this.jsonSchemaErrors, submissionPreview.jsonSchemaErrors) &&
        Objects.equals(this.metadata, submissionPreview.metadata) &&
        Objects.equals(this.password, submissionPreview.password) &&
        Objects.equals(this.processedAt, submissionPreview.processedAt) &&
        Objects.equals(this.state, submissionPreview.state) &&
        Objects.equals(this.templateId, submissionPreview.templateId) &&
        Objects.equals(this.test, submissionPreview.test) &&
        Objects.equals(this.truncatedText, submissionPreview.truncatedText) &&
        Objects.equals(this.pdfHash, submissionPreview.pdfHash) &&
        Objects.equals(this.downloadUrl, submissionPreview.downloadUrl) &&
        Objects.equals(this.permanentDownloadUrl, submissionPreview.permanentDownloadUrl) &&
        Objects.equals(this.previewDownloadUrl, submissionPreview.previewDownloadUrl) &&
        Objects.equals(this.previewGeneratedAt, submissionPreview.previewGeneratedAt) &&
        Objects.equals(this.auditTrailDownloadUrl, submissionPreview.auditTrailDownloadUrl) &&
        Objects.equals(this.actions, submissionPreview.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchId, dataRequests, editable, expired, expiresAt, id, jsonSchemaErrors, metadata, password, processedAt, state, templateId, test, truncatedText, pdfHash, downloadUrl, permanentDownloadUrl, previewDownloadUrl, previewGeneratedAt, auditTrailDownloadUrl, actions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmissionPreview {\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    dataRequests: ").append(toIndentedString(dataRequests)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jsonSchemaErrors: ").append(toIndentedString(jsonSchemaErrors)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    processedAt: ").append(toIndentedString(processedAt)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("    truncatedText: ").append(toIndentedString(truncatedText)).append("\n");
    sb.append("    pdfHash: ").append(toIndentedString(pdfHash)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    permanentDownloadUrl: ").append(toIndentedString(permanentDownloadUrl)).append("\n");
    sb.append("    previewDownloadUrl: ").append(toIndentedString(previewDownloadUrl)).append("\n");
    sb.append("    previewGeneratedAt: ").append(toIndentedString(previewGeneratedAt)).append("\n");
    sb.append("    auditTrailDownloadUrl: ").append(toIndentedString(auditTrailDownloadUrl)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

