/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * SubmissionDataRequestToken
 */
@JsonPropertyOrder({
  SubmissionDataRequestToken.JSON_PROPERTY_ID,
  SubmissionDataRequestToken.JSON_PROPERTY_SECRET,
  SubmissionDataRequestToken.JSON_PROPERTY_EXPIRES_AT,
  SubmissionDataRequestToken.JSON_PROPERTY_DATA_REQUEST_URL
})
@JsonTypeName("submission_data_request_token")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SubmissionDataRequestToken {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @javax.annotation.Nonnull
  private String secret;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @javax.annotation.Nullable
  private String expiresAt;

  public static final String JSON_PROPERTY_DATA_REQUEST_URL = "data_request_url";
  @javax.annotation.Nullable
  private String dataRequestUrl;

  public SubmissionDataRequestToken() { 
  }

  public SubmissionDataRequestToken id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public SubmissionDataRequestToken secret(@javax.annotation.Nonnull String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * Get secret
   * @return secret
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecret(@javax.annotation.Nonnull String secret) {
    this.secret = secret;
  }


  public SubmissionDataRequestToken expiresAt(@javax.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresAt(@javax.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public SubmissionDataRequestToken dataRequestUrl(@javax.annotation.Nullable String dataRequestUrl) {
    this.dataRequestUrl = dataRequestUrl;
    return this;
  }

  /**
   * Get dataRequestUrl
   * @return dataRequestUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_REQUEST_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDataRequestUrl() {
    return dataRequestUrl;
  }


  @JsonProperty(JSON_PROPERTY_DATA_REQUEST_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataRequestUrl(@javax.annotation.Nullable String dataRequestUrl) {
    this.dataRequestUrl = dataRequestUrl;
  }


  /**
   * Return true if this submission_data_request_token object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmissionDataRequestToken submissionDataRequestToken = (SubmissionDataRequestToken) o;
    return Objects.equals(this.id, submissionDataRequestToken.id) &&
        Objects.equals(this.secret, submissionDataRequestToken.secret) &&
        Objects.equals(this.expiresAt, submissionDataRequestToken.expiresAt) &&
        Objects.equals(this.dataRequestUrl, submissionDataRequestToken.dataRequestUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, secret, expiresAt, dataRequestUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmissionDataRequestToken {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    dataRequestUrl: ").append(toIndentedString(dataRequestUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

