/*
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.docspring.JSON;


/**
 * TemplateAddFieldsResponse
 */
@JsonPropertyOrder({
  TemplateAddFieldsResponse.JSON_PROPERTY_STATUS,
  TemplateAddFieldsResponse.JSON_PROPERTY_ERRORS,
  TemplateAddFieldsResponse.JSON_PROPERTY_NEW_FIELD_IDS
})
@JsonTypeName("template_add_fields_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TemplateAddFieldsResponse {
  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    SUCCESS(String.valueOf("success")),
    
    ERROR(String.valueOf("error"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nullable
  private List<String> errors = new ArrayList<>();

  public static final String JSON_PROPERTY_NEW_FIELD_IDS = "new_field_ids";
  @javax.annotation.Nullable
  private List<Integer> newFieldIds = new ArrayList<>();

  public TemplateAddFieldsResponse() { 
  }

  public TemplateAddFieldsResponse status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public TemplateAddFieldsResponse errors(@javax.annotation.Nullable List<String> errors) {
    this.errors = errors;
    return this;
  }

  public TemplateAddFieldsResponse addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getErrors() {
    return errors;
  }


  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@javax.annotation.Nullable List<String> errors) {
    this.errors = errors;
  }


  public TemplateAddFieldsResponse newFieldIds(@javax.annotation.Nullable List<Integer> newFieldIds) {
    this.newFieldIds = newFieldIds;
    return this;
  }

  public TemplateAddFieldsResponse addNewFieldIdsItem(Integer newFieldIdsItem) {
    if (this.newFieldIds == null) {
      this.newFieldIds = new ArrayList<>();
    }
    this.newFieldIds.add(newFieldIdsItem);
    return this;
  }

  /**
   * Get newFieldIds
   * @return newFieldIds
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_FIELD_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getNewFieldIds() {
    return newFieldIds;
  }


  @JsonProperty(JSON_PROPERTY_NEW_FIELD_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewFieldIds(@javax.annotation.Nullable List<Integer> newFieldIds) {
    this.newFieldIds = newFieldIds;
  }


  /**
   * Return true if this template_add_fields_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateAddFieldsResponse templateAddFieldsResponse = (TemplateAddFieldsResponse) o;
    return Objects.equals(this.status, templateAddFieldsResponse.status) &&
        Objects.equals(this.errors, templateAddFieldsResponse.errors) &&
        Objects.equals(this.newFieldIds, templateAddFieldsResponse.newFieldIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, errors, newFieldIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateAddFieldsResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    newFieldIds: ").append(toIndentedString(newFieldIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

