/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * TemplatestemplateIdaddFieldsFields
 */
@javax.annotation.Generated(value = "com.docspring.codegen.DocSpringJavaClientCodegen", date = "2020-11-19T00:04:36.806+08:00[Asia/Kuala_Lumpur]")
public class TemplatestemplateIdaddFieldsFields {
  public static final String SERIALIZED_NAME_BACKGROUND_COLOR_FIELD_NAME = "backgroundColorFieldName";
  @SerializedName(SERIALIZED_NAME_BACKGROUND_COLOR_FIELD_NAME)
  private String backgroundColorFieldName = null;

  public static final String SERIALIZED_NAME_UPPERCASE = "uppercase";
  @SerializedName(SERIALIZED_NAME_UPPERCASE)
  private Boolean uppercase = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private String metadata = null;

  public static final String SERIALIZED_NAME_BARCODE_SYMBOLOGY = "barcodeSymbology";
  @SerializedName(SERIALIZED_NAME_BARCODE_SYMBOLOGY)
  private String barcodeSymbology = null;

  public static final String SERIALIZED_NAME_MIN_LENGTH = "minLength";
  @SerializedName(SERIALIZED_NAME_MIN_LENGTH)
  private BigDecimal minLength = null;

  public static final String SERIALIZED_NAME_INTEGER = "integer";
  @SerializedName(SERIALIZED_NAME_INTEGER)
  private Boolean integer = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    STRING("string"),
    
    NUMBER("number"),
    
    BOOLEAN("boolean"),
    
    DATE("date"),
    
    ADDRESS("address"),
    
    COUNTRY("country"),
    
    EMAIL("email"),
    
    URL("url"),
    
    IMAGE("image"),
    
    SIGNATURE("signature"),
    
    BARCODE("barcode"),
    
    COMBINED("combined");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type = null;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  private Boolean required = null;

  public static final String SERIALIZED_NAME_COMB_VALUE_OFFSET = "combValueOffset";
  @SerializedName(SERIALIZED_NAME_COMB_VALUE_OFFSET)
  private BigDecimal combValueOffset = null;

  /**
   * Gets or Sets imageGravity
   */
  @JsonAdapter(ImageGravityEnum.Adapter.class)
  public enum ImageGravityEnum {
    NORTHWEST("NorthWest"),
    
    NORTH("North"),
    
    NORTHEAST("NorthEast"),
    
    WEST("West"),
    
    CENTER("Center"),
    
    EAST("East"),
    
    SOUTHWEST("SouthWest"),
    
    SOUTH("South"),
    
    SOUTHEAST("SouthEast");

    private String value;

    ImageGravityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ImageGravityEnum fromValue(String text) {
      for (ImageGravityEnum b : ImageGravityEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<ImageGravityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ImageGravityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ImageGravityEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ImageGravityEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_IMAGE_GRAVITY = "imageGravity";
  @SerializedName(SERIALIZED_NAME_IMAGE_GRAVITY)
  private ImageGravityEnum imageGravity = null;

  /**
   * Gets or Sets overflow
   */
  @JsonAdapter(OverflowEnum.Adapter.class)
  public enum OverflowEnum {
    SHRINK_TO_FIT("shrink_to_fit"),
    
    TRUNCATE("truncate");

    private String value;

    OverflowEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OverflowEnum fromValue(String text) {
      for (OverflowEnum b : OverflowEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<OverflowEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OverflowEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OverflowEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OverflowEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_OVERFLOW = "overflow";
  @SerializedName(SERIALIZED_NAME_OVERFLOW)
  private OverflowEnum overflow = null;

  public static final String SERIALIZED_NAME_QRCODE_COLOR = "qrcodeColor";
  @SerializedName(SERIALIZED_NAME_QRCODE_COLOR)
  private String qrcodeColor = null;

  public static final String SERIALIZED_NAME_COLOR_FIELD_REQUIRED = "colorFieldRequired";
  @SerializedName(SERIALIZED_NAME_COLOR_FIELD_REQUIRED)
  private Boolean colorFieldRequired = null;

  public static final String SERIALIZED_NAME_BACKGROUND_COLOR_FIELD_REQUIRED = "backgroundColorFieldRequired";
  @SerializedName(SERIALIZED_NAME_BACKGROUND_COLOR_FIELD_REQUIRED)
  private Boolean backgroundColorFieldRequired = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id = null;

  /**
   * Gets or Sets imageScaleType
   */
  @JsonAdapter(ImageScaleTypeEnum.Adapter.class)
  public enum ImageScaleTypeEnum {
    FIT("fit"),
    
    FILL("fill"),
    
    STRETCH("stretch");

    private String value;

    ImageScaleTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ImageScaleTypeEnum fromValue(String text) {
      for (ImageScaleTypeEnum b : ImageScaleTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<ImageScaleTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ImageScaleTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ImageScaleTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ImageScaleTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_IMAGE_SCALE_TYPE = "imageScaleType";
  @SerializedName(SERIALIZED_NAME_IMAGE_SCALE_TYPE)
  private ImageScaleTypeEnum imageScaleType = null;

  public static final String SERIALIZED_NAME_EXCLUSIVE_MINIMUM = "exclusiveMinimum";
  @SerializedName(SERIALIZED_NAME_EXCLUSIVE_MINIMUM)
  private Boolean exclusiveMinimum = null;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private BigDecimal height = null;

  public static final String SERIALIZED_NAME_NUMBER_CONDITION_RANGE_EXCLUSIVE_MAX = "numberConditionRangeExclusiveMax";
  @SerializedName(SERIALIZED_NAME_NUMBER_CONDITION_RANGE_EXCLUSIVE_MAX)
  private Boolean numberConditionRangeExclusiveMax = null;

  public static final String SERIALIZED_NAME_INVERT_BOOLEAN_CONDITION = "invertBooleanCondition";
  @SerializedName(SERIALIZED_NAME_INVERT_BOOLEAN_CONDITION)
  private Boolean invertBooleanCondition = null;

  public static final String SERIALIZED_NAME_SHAPE_FILL_COLOR_FIELD_NAME = "shapeFillColorFieldName";
  @SerializedName(SERIALIZED_NAME_SHAPE_FILL_COLOR_FIELD_NAME)
  private String shapeFillColorFieldName = null;

  public static final String SERIALIZED_NAME_STATIC = "static";
  @SerializedName(SERIALIZED_NAME_STATIC)
  private Boolean _static = null;

  public static final String SERIALIZED_NAME_SHAPE_BORDER_COLOR_FIELD_NAME = "shapeBorderColorFieldName";
  @SerializedName(SERIALIZED_NAME_SHAPE_BORDER_COLOR_FIELD_NAME)
  private String shapeBorderColorFieldName = null;

  /**
   * Gets or Sets vAlignment
   */
  @JsonAdapter(VAlignmentEnum.Adapter.class)
  public enum VAlignmentEnum {
    BOTTOM("bottom"),
    
    CENTER("center"),
    
    TOP("top");

    private String value;

    VAlignmentEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VAlignmentEnum fromValue(String text) {
      for (VAlignmentEnum b : VAlignmentEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<VAlignmentEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VAlignmentEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VAlignmentEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return VAlignmentEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_V_ALIGNMENT = "vAlignment";
  @SerializedName(SERIALIZED_NAME_V_ALIGNMENT)
  private VAlignmentEnum vAlignment = null;

  public static final String SERIALIZED_NAME_BOLD = "bold";
  @SerializedName(SERIALIZED_NAME_BOLD)
  private Boolean bold = null;

  public static final String SERIALIZED_NAME_SHAPE_BORDER_WIDTH = "shapeBorderWidth";
  @SerializedName(SERIALIZED_NAME_SHAPE_BORDER_WIDTH)
  private BigDecimal shapeBorderWidth = null;

  public static final String SERIALIZED_NAME_COMB_NUMBER_OF_CELLS = "combNumberOfCells";
  @SerializedName(SERIALIZED_NAME_COMB_NUMBER_OF_CELLS)
  private BigDecimal combNumberOfCells = null;

  public static final String SERIALIZED_NAME_SHAPE_BORDER_COLOR = "shapeBorderColor";
  @SerializedName(SERIALIZED_NAME_SHAPE_BORDER_COLOR)
  private String shapeBorderColor = null;

  public static final String SERIALIZED_NAME_COMB = "comb";
  @SerializedName(SERIALIZED_NAME_COMB)
  private Boolean comb = null;

  public static final String SERIALIZED_NAME_TYPEFACE = "typeface";
  @SerializedName(SERIALIZED_NAME_TYPEFACE)
  private String typeface = null;

  /**
   * Gets or Sets shapeType
   */
  @JsonAdapter(ShapeTypeEnum.Adapter.class)
  public enum ShapeTypeEnum {
    SQUARE("square"),
    
    RECTANGLE("rectangle"),
    
    CIRCLE("circle"),
    
    ELLIPSE("ellipse");

    private String value;

    ShapeTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ShapeTypeEnum fromValue(String text) {
      for (ShapeTypeEnum b : ShapeTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<ShapeTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ShapeTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ShapeTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ShapeTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_SHAPE_TYPE = "shapeType";
  @SerializedName(SERIALIZED_NAME_SHAPE_TYPE)
  private ShapeTypeEnum shapeType = null;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  private String condition = null;

  /**
   * Gets or Sets displayType
   */
  @JsonAdapter(DisplayTypeEnum.Adapter.class)
  public enum DisplayTypeEnum {
    TEXT("text"),
    
    CHECK("check"),
    
    QRCODE("qrcode"),
    
    BARCODE("barcode"),
    
    IMAGE("image"),
    
    SHAPE("shape");

    private String value;

    DisplayTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DisplayTypeEnum fromValue(String text) {
      for (DisplayTypeEnum b : DisplayTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<DisplayTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DisplayTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DisplayTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DisplayTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_DISPLAY_TYPE = "displayType";
  @SerializedName(SERIALIZED_NAME_DISPLAY_TYPE)
  private DisplayTypeEnum displayType = null;

  public static final String SERIALIZED_NAME_CHECK_COLOR = "checkColor";
  @SerializedName(SERIALIZED_NAME_CHECK_COLOR)
  private String checkColor = null;

  public static final String SERIALIZED_NAME_MULTILINE_LINES = "multilineLines";
  @SerializedName(SERIALIZED_NAME_MULTILINE_LINES)
  private BigDecimal multilineLines = null;

  public static final String SERIALIZED_NAME_MULTILINE = "multiline";
  @SerializedName(SERIALIZED_NAME_MULTILINE)
  private Boolean multiline = null;

  public static final String SERIALIZED_NAME_TRUE_TEXT = "trueText";
  @SerializedName(SERIALIZED_NAME_TRUE_TEXT)
  private String trueText = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = null;

  public static final String SERIALIZED_NAME_FONT_SIZE = "fontSize";
  @SerializedName(SERIALIZED_NAME_FONT_SIZE)
  private BigDecimal fontSize = null;

  public static final String SERIALIZED_NAME_PAGE = "page";
  @SerializedName(SERIALIZED_NAME_PAGE)
  private BigDecimal page = null;

  /**
   * Gets or Sets alignment
   */
  @JsonAdapter(AlignmentEnum.Adapter.class)
  public enum AlignmentEnum {
    LEFT("left"),
    
    CENTER("center"),
    
    RIGHT("right");

    private String value;

    AlignmentEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AlignmentEnum fromValue(String text) {
      for (AlignmentEnum b : AlignmentEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<AlignmentEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AlignmentEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AlignmentEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AlignmentEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_ALIGNMENT = "alignment";
  @SerializedName(SERIALIZED_NAME_ALIGNMENT)
  private AlignmentEnum alignment = null;

  public static final String SERIALIZED_NAME_MAX_LENGTH = "maxLength";
  @SerializedName(SERIALIZED_NAME_MAX_LENGTH)
  private BigDecimal maxLength = null;

  public static final String SERIALIZED_NAME_AUTO_CALCULATE_MAX_LENGTH = "autoCalculateMaxLength";
  @SerializedName(SERIALIZED_NAME_AUTO_CALCULATE_MAX_LENGTH)
  private Boolean autoCalculateMaxLength = null;

  public static final String SERIALIZED_NAME_COLOR_FIELD_NAME = "colorFieldName";
  @SerializedName(SERIALIZED_NAME_COLOR_FIELD_NAME)
  private String colorFieldName = null;

  public static final String SERIALIZED_NAME_QRCODE_COLOR_FIELD_NAME = "qrcodeColorFieldName";
  @SerializedName(SERIALIZED_NAME_QRCODE_COLOR_FIELD_NAME)
  private String qrcodeColorFieldName = null;

  public static final String SERIALIZED_NAME_NUMBER_CONDITION_RANGE_MIN = "numberConditionRangeMin";
  @SerializedName(SERIALIZED_NAME_NUMBER_CONDITION_RANGE_MIN)
  private BigDecimal numberConditionRangeMin = null;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  private String color = null;

  public static final String SERIALIZED_NAME_HIDDEN = "hidden";
  @SerializedName(SERIALIZED_NAME_HIDDEN)
  private Boolean hidden = null;

  public static final String SERIALIZED_NAME_CHECK_COLOR_FIELD_REQUIRED = "checkColorFieldRequired";
  @SerializedName(SERIALIZED_NAME_CHECK_COLOR_FIELD_REQUIRED)
  private Boolean checkColorFieldRequired = null;

  public static final String SERIALIZED_NAME_COMBINED_FIELD_FORMAT = "combinedFieldFormat";
  @SerializedName(SERIALIZED_NAME_COMBINED_FIELD_FORMAT)
  private String combinedFieldFormat = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description = null;

  public static final String SERIALIZED_NAME_SHAPE_BORDER_COLOR_FIELD_REQUIRED = "shapeBorderColorFieldRequired";
  @SerializedName(SERIALIZED_NAME_SHAPE_BORDER_COLOR_FIELD_REQUIRED)
  private Boolean shapeBorderColorFieldRequired = null;

  public static final String SERIALIZED_NAME_COMBINED_FIELD_NAMES = "combinedFieldNames";
  @SerializedName(SERIALIZED_NAME_COMBINED_FIELD_NAMES)
  private String combinedFieldNames = null;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title = null;

  public static final String SERIALIZED_NAME_NUMBER_CONDITION_RANGE_EXCLUSIVE_MIN = "numberConditionRangeExclusiveMin";
  @SerializedName(SERIALIZED_NAME_NUMBER_CONDITION_RANGE_EXCLUSIVE_MIN)
  private Boolean numberConditionRangeExclusiveMin = null;

  public static final String SERIALIZED_NAME_COMBINED_FIELD_SEPARATOR = "combinedFieldSeparator";
  @SerializedName(SERIALIZED_NAME_COMBINED_FIELD_SEPARATOR)
  private String combinedFieldSeparator = null;

  public static final String SERIALIZED_NAME_EXCLUSIVE_MAXIMUM = "exclusiveMaximum";
  @SerializedName(SERIALIZED_NAME_EXCLUSIVE_MAXIMUM)
  private Boolean exclusiveMaximum = null;

  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  private String _default = null;

  public static final String SERIALIZED_NAME_COMBINED_FIELD_TYPE = "combinedFieldType";
  @SerializedName(SERIALIZED_NAME_COMBINED_FIELD_TYPE)
  private String combinedFieldType = null;

  public static final String SERIALIZED_NAME_DATE_TIME_FORMAT = "dateTimeFormat";
  @SerializedName(SERIALIZED_NAME_DATE_TIME_FORMAT)
  private String dateTimeFormat = null;

  public static final String SERIALIZED_NAME_QRCODE_COLOR_FIELD_REQUIRED = "qrcodeColorFieldRequired";
  @SerializedName(SERIALIZED_NAME_QRCODE_COLOR_FIELD_REQUIRED)
  private Boolean qrcodeColorFieldRequired = null;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private Boolean currency = null;

  public static final String SERIALIZED_NAME_FALSE_TEXT = "falseText";
  @SerializedName(SERIALIZED_NAME_FALSE_TEXT)
  private String falseText = null;

  public static final String SERIALIZED_NAME_STRIKETHROUGH = "strikethrough";
  @SerializedName(SERIALIZED_NAME_STRIKETHROUGH)
  private Boolean strikethrough = null;

  public static final String SERIALIZED_NAME_CHARACTER_SPACING = "characterSpacing";
  @SerializedName(SERIALIZED_NAME_CHARACTER_SPACING)
  private BigDecimal characterSpacing = null;

  public static final String SERIALIZED_NAME_NUMBER_CONDITION_RANGE_MAX = "numberConditionRangeMax";
  @SerializedName(SERIALIZED_NAME_NUMBER_CONDITION_RANGE_MAX)
  private BigDecimal numberConditionRangeMax = null;

  public static final String SERIALIZED_NAME_BACKGROUND_COLOR = "backgroundColor";
  @SerializedName(SERIALIZED_NAME_BACKGROUND_COLOR)
  private String backgroundColor = null;

  public static final String SERIALIZED_NAME_CHECK_COLOR_FIELD_NAME = "checkColorFieldName";
  @SerializedName(SERIALIZED_NAME_CHECK_COLOR_FIELD_NAME)
  private String checkColorFieldName = null;

  /**
   * Gets or Sets checkCharacter
   */
  @JsonAdapter(CheckCharacterEnum.Adapter.class)
  public enum CheckCharacterEnum {
    _10003_("&#10003;"),
    
    _10004_("&#10004;"),
    
    _10006_("&#10006;"),
    
    _10007_("&#10007;"),
    
    _10008_("&#10008;");

    private String value;

    CheckCharacterEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CheckCharacterEnum fromValue(String text) {
      for (CheckCharacterEnum b : CheckCharacterEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<CheckCharacterEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CheckCharacterEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CheckCharacterEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CheckCharacterEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_CHECK_CHARACTER = "checkCharacter";
  @SerializedName(SERIALIZED_NAME_CHECK_CHARACTER)
  private CheckCharacterEnum checkCharacter = null;

  public static final String SERIALIZED_NAME_ROTATION = "rotation";
  @SerializedName(SERIALIZED_NAME_ROTATION)
  private BigDecimal rotation = null;

  public static final String SERIALIZED_NAME_OPTION_LIST = "optionList";
  @SerializedName(SERIALIZED_NAME_OPTION_LIST)
  private String optionList = null;

  public static final String SERIALIZED_NAME_SHAPE_FILL_COLOR = "shapeFillColor";
  @SerializedName(SERIALIZED_NAME_SHAPE_FILL_COLOR)
  private String shapeFillColor = null;

  /**
   * Gets or Sets stringConditionType
   */
  @JsonAdapter(StringConditionTypeEnum.Adapter.class)
  public enum StringConditionTypeEnum {
    EQUALS("equals"),
    
    CONTAINS("contains"),
    
    STARTS_WITH("starts_with"),
    
    ENDS_WITH("ends_with"),
    
    REGEX("regex");

    private String value;

    StringConditionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StringConditionTypeEnum fromValue(String text) {
      for (StringConditionTypeEnum b : StringConditionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<StringConditionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StringConditionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StringConditionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StringConditionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_STRING_CONDITION_TYPE = "stringConditionType";
  @SerializedName(SERIALIZED_NAME_STRING_CONDITION_TYPE)
  private StringConditionTypeEnum stringConditionType = null;

  public static final String SERIALIZED_NAME_SHAPE_FILL_COLOR_FIELD_REQUIRED = "shapeFillColorFieldRequired";
  @SerializedName(SERIALIZED_NAME_SHAPE_FILL_COLOR_FIELD_REQUIRED)
  private Boolean shapeFillColorFieldRequired = null;

  public static final String SERIALIZED_NAME_DECIMAL_PLACES = "decimalPlaces";
  @SerializedName(SERIALIZED_NAME_DECIMAL_PLACES)
  private BigDecimal decimalPlaces = null;

  public static final String SERIALIZED_NAME_INCLUDE_TIME = "includeTime";
  @SerializedName(SERIALIZED_NAME_INCLUDE_TIME)
  private Boolean includeTime = null;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  private BigDecimal width = null;

  public static final String SERIALIZED_NAME_X = "x";
  @SerializedName(SERIALIZED_NAME_X)
  private BigDecimal x = null;

  public static final String SERIALIZED_NAME_MAXIMUM = "maximum";
  @SerializedName(SERIALIZED_NAME_MAXIMUM)
  private BigDecimal maximum = null;

  public static final String SERIALIZED_NAME_Y = "y";
  @SerializedName(SERIALIZED_NAME_Y)
  private BigDecimal y = null;

  public static final String SERIALIZED_NAME_SIGNATURE_ALLOW_DRAW = "signatureAllowDraw";
  @SerializedName(SERIALIZED_NAME_SIGNATURE_ALLOW_DRAW)
  private Boolean signatureAllowDraw = null;

  /**
   * Gets or Sets numberConditionType
   */
  @JsonAdapter(NumberConditionTypeEnum.Adapter.class)
  public enum NumberConditionTypeEnum {
    EQUALS("equals"),
    
    RANGE("range"),
    
    GTE("gte"),
    
    GT("gt"),
    
    LTE("lte"),
    
    LT("lt");

    private String value;

    NumberConditionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NumberConditionTypeEnum fromValue(String text) {
      for (NumberConditionTypeEnum b : NumberConditionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<NumberConditionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NumberConditionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NumberConditionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return NumberConditionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_NUMBER_CONDITION_TYPE = "numberConditionType";
  @SerializedName(SERIALIZED_NAME_NUMBER_CONDITION_TYPE)
  private NumberConditionTypeEnum numberConditionType = null;

  public static final String SERIALIZED_NAME_OPACITY = "opacity";
  @SerializedName(SERIALIZED_NAME_OPACITY)
  private BigDecimal opacity = null;

  public static final String SERIALIZED_NAME_MINIMUM = "minimum";
  @SerializedName(SERIALIZED_NAME_MINIMUM)
  private BigDecimal minimum = null;

  public static final String SERIALIZED_NAME_SIGNATURE_ALLOW_TYPE = "signatureAllowType";
  @SerializedName(SERIALIZED_NAME_SIGNATURE_ALLOW_TYPE)
  private Boolean signatureAllowType = null;

  public TemplatestemplateIdaddFieldsFields backgroundColorFieldName(String backgroundColorFieldName) {
    this.backgroundColorFieldName = backgroundColorFieldName;
    return this;
  }

   /**
   * Get backgroundColorFieldName
   * @return backgroundColorFieldName
  **/
  @ApiModelProperty(value = "")
  public String getBackgroundColorFieldName() {
    return backgroundColorFieldName;
  }

  public void setBackgroundColorFieldName(String backgroundColorFieldName) {
    this.backgroundColorFieldName = backgroundColorFieldName;
  }

  public TemplatestemplateIdaddFieldsFields uppercase(Boolean uppercase) {
    this.uppercase = uppercase;
    return this;
  }

   /**
   * Get uppercase
   * @return uppercase
  **/
  @ApiModelProperty(value = "")
  public Boolean getUppercase() {
    return uppercase;
  }

  public void setUppercase(Boolean uppercase) {
    this.uppercase = uppercase;
  }

  public TemplatestemplateIdaddFieldsFields metadata(String metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public String getMetadata() {
    return metadata;
  }

  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }

  public TemplatestemplateIdaddFieldsFields barcodeSymbology(String barcodeSymbology) {
    this.barcodeSymbology = barcodeSymbology;
    return this;
  }

   /**
   * Get barcodeSymbology
   * @return barcodeSymbology
  **/
  @ApiModelProperty(value = "")
  public String getBarcodeSymbology() {
    return barcodeSymbology;
  }

  public void setBarcodeSymbology(String barcodeSymbology) {
    this.barcodeSymbology = barcodeSymbology;
  }

  public TemplatestemplateIdaddFieldsFields minLength(BigDecimal minLength) {
    this.minLength = minLength;
    return this;
  }

   /**
   * Get minLength
   * @return minLength
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMinLength() {
    return minLength;
  }

  public void setMinLength(BigDecimal minLength) {
    this.minLength = minLength;
  }

  public TemplatestemplateIdaddFieldsFields integer(Boolean integer) {
    this.integer = integer;
    return this;
  }

   /**
   * Get integer
   * @return integer
  **/
  @ApiModelProperty(value = "")
  public Boolean getInteger() {
    return integer;
  }

  public void setInteger(Boolean integer) {
    this.integer = integer;
  }

  public TemplatestemplateIdaddFieldsFields type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public TemplatestemplateIdaddFieldsFields required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  @ApiModelProperty(value = "")
  public Boolean getRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }

  public TemplatestemplateIdaddFieldsFields combValueOffset(BigDecimal combValueOffset) {
    this.combValueOffset = combValueOffset;
    return this;
  }

   /**
   * Get combValueOffset
   * @return combValueOffset
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCombValueOffset() {
    return combValueOffset;
  }

  public void setCombValueOffset(BigDecimal combValueOffset) {
    this.combValueOffset = combValueOffset;
  }

  public TemplatestemplateIdaddFieldsFields imageGravity(ImageGravityEnum imageGravity) {
    this.imageGravity = imageGravity;
    return this;
  }

   /**
   * Get imageGravity
   * @return imageGravity
  **/
  @ApiModelProperty(value = "")
  public ImageGravityEnum getImageGravity() {
    return imageGravity;
  }

  public void setImageGravity(ImageGravityEnum imageGravity) {
    this.imageGravity = imageGravity;
  }

  public TemplatestemplateIdaddFieldsFields overflow(OverflowEnum overflow) {
    this.overflow = overflow;
    return this;
  }

   /**
   * Get overflow
   * @return overflow
  **/
  @ApiModelProperty(value = "")
  public OverflowEnum getOverflow() {
    return overflow;
  }

  public void setOverflow(OverflowEnum overflow) {
    this.overflow = overflow;
  }

  public TemplatestemplateIdaddFieldsFields qrcodeColor(String qrcodeColor) {
    this.qrcodeColor = qrcodeColor;
    return this;
  }

   /**
   * Get qrcodeColor
   * @return qrcodeColor
  **/
  @ApiModelProperty(value = "")
  public String getQrcodeColor() {
    return qrcodeColor;
  }

  public void setQrcodeColor(String qrcodeColor) {
    this.qrcodeColor = qrcodeColor;
  }

  public TemplatestemplateIdaddFieldsFields colorFieldRequired(Boolean colorFieldRequired) {
    this.colorFieldRequired = colorFieldRequired;
    return this;
  }

   /**
   * Get colorFieldRequired
   * @return colorFieldRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getColorFieldRequired() {
    return colorFieldRequired;
  }

  public void setColorFieldRequired(Boolean colorFieldRequired) {
    this.colorFieldRequired = colorFieldRequired;
  }

  public TemplatestemplateIdaddFieldsFields backgroundColorFieldRequired(Boolean backgroundColorFieldRequired) {
    this.backgroundColorFieldRequired = backgroundColorFieldRequired;
    return this;
  }

   /**
   * Get backgroundColorFieldRequired
   * @return backgroundColorFieldRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getBackgroundColorFieldRequired() {
    return backgroundColorFieldRequired;
  }

  public void setBackgroundColorFieldRequired(Boolean backgroundColorFieldRequired) {
    this.backgroundColorFieldRequired = backgroundColorFieldRequired;
  }

  public TemplatestemplateIdaddFieldsFields id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * minimum: 0
   * @return id
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public TemplatestemplateIdaddFieldsFields imageScaleType(ImageScaleTypeEnum imageScaleType) {
    this.imageScaleType = imageScaleType;
    return this;
  }

   /**
   * Get imageScaleType
   * @return imageScaleType
  **/
  @ApiModelProperty(value = "")
  public ImageScaleTypeEnum getImageScaleType() {
    return imageScaleType;
  }

  public void setImageScaleType(ImageScaleTypeEnum imageScaleType) {
    this.imageScaleType = imageScaleType;
  }

  public TemplatestemplateIdaddFieldsFields exclusiveMinimum(Boolean exclusiveMinimum) {
    this.exclusiveMinimum = exclusiveMinimum;
    return this;
  }

   /**
   * Get exclusiveMinimum
   * @return exclusiveMinimum
  **/
  @ApiModelProperty(value = "")
  public Boolean getExclusiveMinimum() {
    return exclusiveMinimum;
  }

  public void setExclusiveMinimum(Boolean exclusiveMinimum) {
    this.exclusiveMinimum = exclusiveMinimum;
  }

  public TemplatestemplateIdaddFieldsFields height(BigDecimal height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * minimum: 0
   * @return height
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getHeight() {
    return height;
  }

  public void setHeight(BigDecimal height) {
    this.height = height;
  }

  public TemplatestemplateIdaddFieldsFields numberConditionRangeExclusiveMax(Boolean numberConditionRangeExclusiveMax) {
    this.numberConditionRangeExclusiveMax = numberConditionRangeExclusiveMax;
    return this;
  }

   /**
   * Get numberConditionRangeExclusiveMax
   * @return numberConditionRangeExclusiveMax
  **/
  @ApiModelProperty(value = "")
  public Boolean getNumberConditionRangeExclusiveMax() {
    return numberConditionRangeExclusiveMax;
  }

  public void setNumberConditionRangeExclusiveMax(Boolean numberConditionRangeExclusiveMax) {
    this.numberConditionRangeExclusiveMax = numberConditionRangeExclusiveMax;
  }

  public TemplatestemplateIdaddFieldsFields invertBooleanCondition(Boolean invertBooleanCondition) {
    this.invertBooleanCondition = invertBooleanCondition;
    return this;
  }

   /**
   * Get invertBooleanCondition
   * @return invertBooleanCondition
  **/
  @ApiModelProperty(value = "")
  public Boolean getInvertBooleanCondition() {
    return invertBooleanCondition;
  }

  public void setInvertBooleanCondition(Boolean invertBooleanCondition) {
    this.invertBooleanCondition = invertBooleanCondition;
  }

  public TemplatestemplateIdaddFieldsFields shapeFillColorFieldName(String shapeFillColorFieldName) {
    this.shapeFillColorFieldName = shapeFillColorFieldName;
    return this;
  }

   /**
   * Get shapeFillColorFieldName
   * @return shapeFillColorFieldName
  **/
  @ApiModelProperty(value = "")
  public String getShapeFillColorFieldName() {
    return shapeFillColorFieldName;
  }

  public void setShapeFillColorFieldName(String shapeFillColorFieldName) {
    this.shapeFillColorFieldName = shapeFillColorFieldName;
  }

  public TemplatestemplateIdaddFieldsFields _static(Boolean _static) {
    this._static = _static;
    return this;
  }

   /**
   * Get _static
   * @return _static
  **/
  @ApiModelProperty(value = "")
  public Boolean getStatic() {
    return _static;
  }

  public void setStatic(Boolean _static) {
    this._static = _static;
  }

  public TemplatestemplateIdaddFieldsFields shapeBorderColorFieldName(String shapeBorderColorFieldName) {
    this.shapeBorderColorFieldName = shapeBorderColorFieldName;
    return this;
  }

   /**
   * Get shapeBorderColorFieldName
   * @return shapeBorderColorFieldName
  **/
  @ApiModelProperty(value = "")
  public String getShapeBorderColorFieldName() {
    return shapeBorderColorFieldName;
  }

  public void setShapeBorderColorFieldName(String shapeBorderColorFieldName) {
    this.shapeBorderColorFieldName = shapeBorderColorFieldName;
  }

  public TemplatestemplateIdaddFieldsFields vAlignment(VAlignmentEnum vAlignment) {
    this.vAlignment = vAlignment;
    return this;
  }

   /**
   * Get vAlignment
   * @return vAlignment
  **/
  @ApiModelProperty(value = "")
  public VAlignmentEnum getVAlignment() {
    return vAlignment;
  }

  public void setVAlignment(VAlignmentEnum vAlignment) {
    this.vAlignment = vAlignment;
  }

  public TemplatestemplateIdaddFieldsFields bold(Boolean bold) {
    this.bold = bold;
    return this;
  }

   /**
   * Get bold
   * @return bold
  **/
  @ApiModelProperty(value = "")
  public Boolean getBold() {
    return bold;
  }

  public void setBold(Boolean bold) {
    this.bold = bold;
  }

  public TemplatestemplateIdaddFieldsFields shapeBorderWidth(BigDecimal shapeBorderWidth) {
    this.shapeBorderWidth = shapeBorderWidth;
    return this;
  }

   /**
   * Get shapeBorderWidth
   * minimum: 0
   * @return shapeBorderWidth
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getShapeBorderWidth() {
    return shapeBorderWidth;
  }

  public void setShapeBorderWidth(BigDecimal shapeBorderWidth) {
    this.shapeBorderWidth = shapeBorderWidth;
  }

  public TemplatestemplateIdaddFieldsFields combNumberOfCells(BigDecimal combNumberOfCells) {
    this.combNumberOfCells = combNumberOfCells;
    return this;
  }

   /**
   * Get combNumberOfCells
   * minimum: 0
   * @return combNumberOfCells
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCombNumberOfCells() {
    return combNumberOfCells;
  }

  public void setCombNumberOfCells(BigDecimal combNumberOfCells) {
    this.combNumberOfCells = combNumberOfCells;
  }

  public TemplatestemplateIdaddFieldsFields shapeBorderColor(String shapeBorderColor) {
    this.shapeBorderColor = shapeBorderColor;
    return this;
  }

   /**
   * Get shapeBorderColor
   * @return shapeBorderColor
  **/
  @ApiModelProperty(value = "")
  public String getShapeBorderColor() {
    return shapeBorderColor;
  }

  public void setShapeBorderColor(String shapeBorderColor) {
    this.shapeBorderColor = shapeBorderColor;
  }

  public TemplatestemplateIdaddFieldsFields comb(Boolean comb) {
    this.comb = comb;
    return this;
  }

   /**
   * Get comb
   * @return comb
  **/
  @ApiModelProperty(value = "")
  public Boolean getComb() {
    return comb;
  }

  public void setComb(Boolean comb) {
    this.comb = comb;
  }

  public TemplatestemplateIdaddFieldsFields typeface(String typeface) {
    this.typeface = typeface;
    return this;
  }

   /**
   * Get typeface
   * @return typeface
  **/
  @ApiModelProperty(value = "")
  public String getTypeface() {
    return typeface;
  }

  public void setTypeface(String typeface) {
    this.typeface = typeface;
  }

  public TemplatestemplateIdaddFieldsFields shapeType(ShapeTypeEnum shapeType) {
    this.shapeType = shapeType;
    return this;
  }

   /**
   * Get shapeType
   * @return shapeType
  **/
  @ApiModelProperty(value = "")
  public ShapeTypeEnum getShapeType() {
    return shapeType;
  }

  public void setShapeType(ShapeTypeEnum shapeType) {
    this.shapeType = shapeType;
  }

  public TemplatestemplateIdaddFieldsFields condition(String condition) {
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  @ApiModelProperty(value = "")
  public String getCondition() {
    return condition;
  }

  public void setCondition(String condition) {
    this.condition = condition;
  }

  public TemplatestemplateIdaddFieldsFields displayType(DisplayTypeEnum displayType) {
    this.displayType = displayType;
    return this;
  }

   /**
   * Get displayType
   * @return displayType
  **/
  @ApiModelProperty(value = "")
  public DisplayTypeEnum getDisplayType() {
    return displayType;
  }

  public void setDisplayType(DisplayTypeEnum displayType) {
    this.displayType = displayType;
  }

  public TemplatestemplateIdaddFieldsFields checkColor(String checkColor) {
    this.checkColor = checkColor;
    return this;
  }

   /**
   * Get checkColor
   * @return checkColor
  **/
  @ApiModelProperty(value = "")
  public String getCheckColor() {
    return checkColor;
  }

  public void setCheckColor(String checkColor) {
    this.checkColor = checkColor;
  }

  public TemplatestemplateIdaddFieldsFields multilineLines(BigDecimal multilineLines) {
    this.multilineLines = multilineLines;
    return this;
  }

   /**
   * Get multilineLines
   * minimum: 0
   * @return multilineLines
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMultilineLines() {
    return multilineLines;
  }

  public void setMultilineLines(BigDecimal multilineLines) {
    this.multilineLines = multilineLines;
  }

  public TemplatestemplateIdaddFieldsFields multiline(Boolean multiline) {
    this.multiline = multiline;
    return this;
  }

   /**
   * Get multiline
   * @return multiline
  **/
  @ApiModelProperty(value = "")
  public Boolean getMultiline() {
    return multiline;
  }

  public void setMultiline(Boolean multiline) {
    this.multiline = multiline;
  }

  public TemplatestemplateIdaddFieldsFields trueText(String trueText) {
    this.trueText = trueText;
    return this;
  }

   /**
   * Get trueText
   * @return trueText
  **/
  @ApiModelProperty(value = "")
  public String getTrueText() {
    return trueText;
  }

  public void setTrueText(String trueText) {
    this.trueText = trueText;
  }

  public TemplatestemplateIdaddFieldsFields name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TemplatestemplateIdaddFieldsFields fontSize(BigDecimal fontSize) {
    this.fontSize = fontSize;
    return this;
  }

   /**
   * Get fontSize
   * minimum: 0
   * @return fontSize
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getFontSize() {
    return fontSize;
  }

  public void setFontSize(BigDecimal fontSize) {
    this.fontSize = fontSize;
  }

  public TemplatestemplateIdaddFieldsFields page(BigDecimal page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * minimum: 1
   * @return page
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPage() {
    return page;
  }

  public void setPage(BigDecimal page) {
    this.page = page;
  }

  public TemplatestemplateIdaddFieldsFields alignment(AlignmentEnum alignment) {
    this.alignment = alignment;
    return this;
  }

   /**
   * Get alignment
   * @return alignment
  **/
  @ApiModelProperty(value = "")
  public AlignmentEnum getAlignment() {
    return alignment;
  }

  public void setAlignment(AlignmentEnum alignment) {
    this.alignment = alignment;
  }

  public TemplatestemplateIdaddFieldsFields maxLength(BigDecimal maxLength) {
    this.maxLength = maxLength;
    return this;
  }

   /**
   * Get maxLength
   * @return maxLength
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaxLength() {
    return maxLength;
  }

  public void setMaxLength(BigDecimal maxLength) {
    this.maxLength = maxLength;
  }

  public TemplatestemplateIdaddFieldsFields autoCalculateMaxLength(Boolean autoCalculateMaxLength) {
    this.autoCalculateMaxLength = autoCalculateMaxLength;
    return this;
  }

   /**
   * Get autoCalculateMaxLength
   * @return autoCalculateMaxLength
  **/
  @ApiModelProperty(value = "")
  public Boolean getAutoCalculateMaxLength() {
    return autoCalculateMaxLength;
  }

  public void setAutoCalculateMaxLength(Boolean autoCalculateMaxLength) {
    this.autoCalculateMaxLength = autoCalculateMaxLength;
  }

  public TemplatestemplateIdaddFieldsFields colorFieldName(String colorFieldName) {
    this.colorFieldName = colorFieldName;
    return this;
  }

   /**
   * Get colorFieldName
   * @return colorFieldName
  **/
  @ApiModelProperty(value = "")
  public String getColorFieldName() {
    return colorFieldName;
  }

  public void setColorFieldName(String colorFieldName) {
    this.colorFieldName = colorFieldName;
  }

  public TemplatestemplateIdaddFieldsFields qrcodeColorFieldName(String qrcodeColorFieldName) {
    this.qrcodeColorFieldName = qrcodeColorFieldName;
    return this;
  }

   /**
   * Get qrcodeColorFieldName
   * @return qrcodeColorFieldName
  **/
  @ApiModelProperty(value = "")
  public String getQrcodeColorFieldName() {
    return qrcodeColorFieldName;
  }

  public void setQrcodeColorFieldName(String qrcodeColorFieldName) {
    this.qrcodeColorFieldName = qrcodeColorFieldName;
  }

  public TemplatestemplateIdaddFieldsFields numberConditionRangeMin(BigDecimal numberConditionRangeMin) {
    this.numberConditionRangeMin = numberConditionRangeMin;
    return this;
  }

   /**
   * Get numberConditionRangeMin
   * @return numberConditionRangeMin
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getNumberConditionRangeMin() {
    return numberConditionRangeMin;
  }

  public void setNumberConditionRangeMin(BigDecimal numberConditionRangeMin) {
    this.numberConditionRangeMin = numberConditionRangeMin;
  }

  public TemplatestemplateIdaddFieldsFields color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public TemplatestemplateIdaddFieldsFields hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Get hidden
   * @return hidden
  **/
  @ApiModelProperty(value = "")
  public Boolean getHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public TemplatestemplateIdaddFieldsFields checkColorFieldRequired(Boolean checkColorFieldRequired) {
    this.checkColorFieldRequired = checkColorFieldRequired;
    return this;
  }

   /**
   * Get checkColorFieldRequired
   * @return checkColorFieldRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getCheckColorFieldRequired() {
    return checkColorFieldRequired;
  }

  public void setCheckColorFieldRequired(Boolean checkColorFieldRequired) {
    this.checkColorFieldRequired = checkColorFieldRequired;
  }

  public TemplatestemplateIdaddFieldsFields combinedFieldFormat(String combinedFieldFormat) {
    this.combinedFieldFormat = combinedFieldFormat;
    return this;
  }

   /**
   * Get combinedFieldFormat
   * @return combinedFieldFormat
  **/
  @ApiModelProperty(value = "")
  public String getCombinedFieldFormat() {
    return combinedFieldFormat;
  }

  public void setCombinedFieldFormat(String combinedFieldFormat) {
    this.combinedFieldFormat = combinedFieldFormat;
  }

  public TemplatestemplateIdaddFieldsFields description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TemplatestemplateIdaddFieldsFields shapeBorderColorFieldRequired(Boolean shapeBorderColorFieldRequired) {
    this.shapeBorderColorFieldRequired = shapeBorderColorFieldRequired;
    return this;
  }

   /**
   * Get shapeBorderColorFieldRequired
   * @return shapeBorderColorFieldRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getShapeBorderColorFieldRequired() {
    return shapeBorderColorFieldRequired;
  }

  public void setShapeBorderColorFieldRequired(Boolean shapeBorderColorFieldRequired) {
    this.shapeBorderColorFieldRequired = shapeBorderColorFieldRequired;
  }

  public TemplatestemplateIdaddFieldsFields combinedFieldNames(String combinedFieldNames) {
    this.combinedFieldNames = combinedFieldNames;
    return this;
  }

   /**
   * Get combinedFieldNames
   * @return combinedFieldNames
  **/
  @ApiModelProperty(value = "")
  public String getCombinedFieldNames() {
    return combinedFieldNames;
  }

  public void setCombinedFieldNames(String combinedFieldNames) {
    this.combinedFieldNames = combinedFieldNames;
  }

  public TemplatestemplateIdaddFieldsFields title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public TemplatestemplateIdaddFieldsFields numberConditionRangeExclusiveMin(Boolean numberConditionRangeExclusiveMin) {
    this.numberConditionRangeExclusiveMin = numberConditionRangeExclusiveMin;
    return this;
  }

   /**
   * Get numberConditionRangeExclusiveMin
   * @return numberConditionRangeExclusiveMin
  **/
  @ApiModelProperty(value = "")
  public Boolean getNumberConditionRangeExclusiveMin() {
    return numberConditionRangeExclusiveMin;
  }

  public void setNumberConditionRangeExclusiveMin(Boolean numberConditionRangeExclusiveMin) {
    this.numberConditionRangeExclusiveMin = numberConditionRangeExclusiveMin;
  }

  public TemplatestemplateIdaddFieldsFields combinedFieldSeparator(String combinedFieldSeparator) {
    this.combinedFieldSeparator = combinedFieldSeparator;
    return this;
  }

   /**
   * Get combinedFieldSeparator
   * @return combinedFieldSeparator
  **/
  @ApiModelProperty(value = "")
  public String getCombinedFieldSeparator() {
    return combinedFieldSeparator;
  }

  public void setCombinedFieldSeparator(String combinedFieldSeparator) {
    this.combinedFieldSeparator = combinedFieldSeparator;
  }

  public TemplatestemplateIdaddFieldsFields exclusiveMaximum(Boolean exclusiveMaximum) {
    this.exclusiveMaximum = exclusiveMaximum;
    return this;
  }

   /**
   * Get exclusiveMaximum
   * @return exclusiveMaximum
  **/
  @ApiModelProperty(value = "")
  public Boolean getExclusiveMaximum() {
    return exclusiveMaximum;
  }

  public void setExclusiveMaximum(Boolean exclusiveMaximum) {
    this.exclusiveMaximum = exclusiveMaximum;
  }

  public TemplatestemplateIdaddFieldsFields _default(String _default) {
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @ApiModelProperty(value = "")
  public String getDefault() {
    return _default;
  }

  public void setDefault(String _default) {
    this._default = _default;
  }

  public TemplatestemplateIdaddFieldsFields combinedFieldType(String combinedFieldType) {
    this.combinedFieldType = combinedFieldType;
    return this;
  }

   /**
   * Get combinedFieldType
   * @return combinedFieldType
  **/
  @ApiModelProperty(value = "")
  public String getCombinedFieldType() {
    return combinedFieldType;
  }

  public void setCombinedFieldType(String combinedFieldType) {
    this.combinedFieldType = combinedFieldType;
  }

  public TemplatestemplateIdaddFieldsFields dateTimeFormat(String dateTimeFormat) {
    this.dateTimeFormat = dateTimeFormat;
    return this;
  }

   /**
   * Get dateTimeFormat
   * @return dateTimeFormat
  **/
  @ApiModelProperty(value = "")
  public String getDateTimeFormat() {
    return dateTimeFormat;
  }

  public void setDateTimeFormat(String dateTimeFormat) {
    this.dateTimeFormat = dateTimeFormat;
  }

  public TemplatestemplateIdaddFieldsFields qrcodeColorFieldRequired(Boolean qrcodeColorFieldRequired) {
    this.qrcodeColorFieldRequired = qrcodeColorFieldRequired;
    return this;
  }

   /**
   * Get qrcodeColorFieldRequired
   * @return qrcodeColorFieldRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getQrcodeColorFieldRequired() {
    return qrcodeColorFieldRequired;
  }

  public void setQrcodeColorFieldRequired(Boolean qrcodeColorFieldRequired) {
    this.qrcodeColorFieldRequired = qrcodeColorFieldRequired;
  }

  public TemplatestemplateIdaddFieldsFields currency(Boolean currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public Boolean getCurrency() {
    return currency;
  }

  public void setCurrency(Boolean currency) {
    this.currency = currency;
  }

  public TemplatestemplateIdaddFieldsFields falseText(String falseText) {
    this.falseText = falseText;
    return this;
  }

   /**
   * Get falseText
   * @return falseText
  **/
  @ApiModelProperty(value = "")
  public String getFalseText() {
    return falseText;
  }

  public void setFalseText(String falseText) {
    this.falseText = falseText;
  }

  public TemplatestemplateIdaddFieldsFields strikethrough(Boolean strikethrough) {
    this.strikethrough = strikethrough;
    return this;
  }

   /**
   * Get strikethrough
   * @return strikethrough
  **/
  @ApiModelProperty(value = "")
  public Boolean getStrikethrough() {
    return strikethrough;
  }

  public void setStrikethrough(Boolean strikethrough) {
    this.strikethrough = strikethrough;
  }

  public TemplatestemplateIdaddFieldsFields characterSpacing(BigDecimal characterSpacing) {
    this.characterSpacing = characterSpacing;
    return this;
  }

   /**
   * Get characterSpacing
   * @return characterSpacing
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCharacterSpacing() {
    return characterSpacing;
  }

  public void setCharacterSpacing(BigDecimal characterSpacing) {
    this.characterSpacing = characterSpacing;
  }

  public TemplatestemplateIdaddFieldsFields numberConditionRangeMax(BigDecimal numberConditionRangeMax) {
    this.numberConditionRangeMax = numberConditionRangeMax;
    return this;
  }

   /**
   * Get numberConditionRangeMax
   * @return numberConditionRangeMax
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getNumberConditionRangeMax() {
    return numberConditionRangeMax;
  }

  public void setNumberConditionRangeMax(BigDecimal numberConditionRangeMax) {
    this.numberConditionRangeMax = numberConditionRangeMax;
  }

  public TemplatestemplateIdaddFieldsFields backgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
    return this;
  }

   /**
   * Get backgroundColor
   * @return backgroundColor
  **/
  @ApiModelProperty(value = "")
  public String getBackgroundColor() {
    return backgroundColor;
  }

  public void setBackgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
  }

  public TemplatestemplateIdaddFieldsFields checkColorFieldName(String checkColorFieldName) {
    this.checkColorFieldName = checkColorFieldName;
    return this;
  }

   /**
   * Get checkColorFieldName
   * @return checkColorFieldName
  **/
  @ApiModelProperty(value = "")
  public String getCheckColorFieldName() {
    return checkColorFieldName;
  }

  public void setCheckColorFieldName(String checkColorFieldName) {
    this.checkColorFieldName = checkColorFieldName;
  }

  public TemplatestemplateIdaddFieldsFields checkCharacter(CheckCharacterEnum checkCharacter) {
    this.checkCharacter = checkCharacter;
    return this;
  }

   /**
   * Get checkCharacter
   * @return checkCharacter
  **/
  @ApiModelProperty(value = "")
  public CheckCharacterEnum getCheckCharacter() {
    return checkCharacter;
  }

  public void setCheckCharacter(CheckCharacterEnum checkCharacter) {
    this.checkCharacter = checkCharacter;
  }

  public TemplatestemplateIdaddFieldsFields rotation(BigDecimal rotation) {
    this.rotation = rotation;
    return this;
  }

   /**
   * Get rotation
   * minimum: 0
   * maximum: 3.6E+2
   * @return rotation
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRotation() {
    return rotation;
  }

  public void setRotation(BigDecimal rotation) {
    this.rotation = rotation;
  }

  public TemplatestemplateIdaddFieldsFields optionList(String optionList) {
    this.optionList = optionList;
    return this;
  }

   /**
   * Get optionList
   * @return optionList
  **/
  @ApiModelProperty(value = "")
  public String getOptionList() {
    return optionList;
  }

  public void setOptionList(String optionList) {
    this.optionList = optionList;
  }

  public TemplatestemplateIdaddFieldsFields shapeFillColor(String shapeFillColor) {
    this.shapeFillColor = shapeFillColor;
    return this;
  }

   /**
   * Get shapeFillColor
   * @return shapeFillColor
  **/
  @ApiModelProperty(value = "")
  public String getShapeFillColor() {
    return shapeFillColor;
  }

  public void setShapeFillColor(String shapeFillColor) {
    this.shapeFillColor = shapeFillColor;
  }

  public TemplatestemplateIdaddFieldsFields stringConditionType(StringConditionTypeEnum stringConditionType) {
    this.stringConditionType = stringConditionType;
    return this;
  }

   /**
   * Get stringConditionType
   * @return stringConditionType
  **/
  @ApiModelProperty(value = "")
  public StringConditionTypeEnum getStringConditionType() {
    return stringConditionType;
  }

  public void setStringConditionType(StringConditionTypeEnum stringConditionType) {
    this.stringConditionType = stringConditionType;
  }

  public TemplatestemplateIdaddFieldsFields shapeFillColorFieldRequired(Boolean shapeFillColorFieldRequired) {
    this.shapeFillColorFieldRequired = shapeFillColorFieldRequired;
    return this;
  }

   /**
   * Get shapeFillColorFieldRequired
   * @return shapeFillColorFieldRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getShapeFillColorFieldRequired() {
    return shapeFillColorFieldRequired;
  }

  public void setShapeFillColorFieldRequired(Boolean shapeFillColorFieldRequired) {
    this.shapeFillColorFieldRequired = shapeFillColorFieldRequired;
  }

  public TemplatestemplateIdaddFieldsFields decimalPlaces(BigDecimal decimalPlaces) {
    this.decimalPlaces = decimalPlaces;
    return this;
  }

   /**
   * Get decimalPlaces
   * minimum: 0
   * @return decimalPlaces
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDecimalPlaces() {
    return decimalPlaces;
  }

  public void setDecimalPlaces(BigDecimal decimalPlaces) {
    this.decimalPlaces = decimalPlaces;
  }

  public TemplatestemplateIdaddFieldsFields includeTime(Boolean includeTime) {
    this.includeTime = includeTime;
    return this;
  }

   /**
   * Get includeTime
   * @return includeTime
  **/
  @ApiModelProperty(value = "")
  public Boolean getIncludeTime() {
    return includeTime;
  }

  public void setIncludeTime(Boolean includeTime) {
    this.includeTime = includeTime;
  }

  public TemplatestemplateIdaddFieldsFields width(BigDecimal width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * minimum: 0
   * @return width
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getWidth() {
    return width;
  }

  public void setWidth(BigDecimal width) {
    this.width = width;
  }

  public TemplatestemplateIdaddFieldsFields x(BigDecimal x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * minimum: 0
   * @return x
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getX() {
    return x;
  }

  public void setX(BigDecimal x) {
    this.x = x;
  }

  public TemplatestemplateIdaddFieldsFields maximum(BigDecimal maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * Get maximum
   * @return maximum
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaximum() {
    return maximum;
  }

  public void setMaximum(BigDecimal maximum) {
    this.maximum = maximum;
  }

  public TemplatestemplateIdaddFieldsFields y(BigDecimal y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * minimum: 0
   * @return y
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getY() {
    return y;
  }

  public void setY(BigDecimal y) {
    this.y = y;
  }

  public TemplatestemplateIdaddFieldsFields signatureAllowDraw(Boolean signatureAllowDraw) {
    this.signatureAllowDraw = signatureAllowDraw;
    return this;
  }

   /**
   * Get signatureAllowDraw
   * @return signatureAllowDraw
  **/
  @ApiModelProperty(value = "")
  public Boolean getSignatureAllowDraw() {
    return signatureAllowDraw;
  }

  public void setSignatureAllowDraw(Boolean signatureAllowDraw) {
    this.signatureAllowDraw = signatureAllowDraw;
  }

  public TemplatestemplateIdaddFieldsFields numberConditionType(NumberConditionTypeEnum numberConditionType) {
    this.numberConditionType = numberConditionType;
    return this;
  }

   /**
   * Get numberConditionType
   * @return numberConditionType
  **/
  @ApiModelProperty(value = "")
  public NumberConditionTypeEnum getNumberConditionType() {
    return numberConditionType;
  }

  public void setNumberConditionType(NumberConditionTypeEnum numberConditionType) {
    this.numberConditionType = numberConditionType;
  }

  public TemplatestemplateIdaddFieldsFields opacity(BigDecimal opacity) {
    this.opacity = opacity;
    return this;
  }

   /**
   * Get opacity
   * minimum: 0
   * maximum: 1
   * @return opacity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getOpacity() {
    return opacity;
  }

  public void setOpacity(BigDecimal opacity) {
    this.opacity = opacity;
  }

  public TemplatestemplateIdaddFieldsFields minimum(BigDecimal minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * Get minimum
   * @return minimum
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMinimum() {
    return minimum;
  }

  public void setMinimum(BigDecimal minimum) {
    this.minimum = minimum;
  }

  public TemplatestemplateIdaddFieldsFields signatureAllowType(Boolean signatureAllowType) {
    this.signatureAllowType = signatureAllowType;
    return this;
  }

   /**
   * Get signatureAllowType
   * @return signatureAllowType
  **/
  @ApiModelProperty(value = "")
  public Boolean getSignatureAllowType() {
    return signatureAllowType;
  }

  public void setSignatureAllowType(Boolean signatureAllowType) {
    this.signatureAllowType = signatureAllowType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatestemplateIdaddFieldsFields templatestemplateIdaddFieldsFields = (TemplatestemplateIdaddFieldsFields) o;
    return Objects.equals(this.backgroundColorFieldName, templatestemplateIdaddFieldsFields.backgroundColorFieldName) &&
        Objects.equals(this.uppercase, templatestemplateIdaddFieldsFields.uppercase) &&
        Objects.equals(this.metadata, templatestemplateIdaddFieldsFields.metadata) &&
        Objects.equals(this.barcodeSymbology, templatestemplateIdaddFieldsFields.barcodeSymbology) &&
        Objects.equals(this.minLength, templatestemplateIdaddFieldsFields.minLength) &&
        Objects.equals(this.integer, templatestemplateIdaddFieldsFields.integer) &&
        Objects.equals(this.type, templatestemplateIdaddFieldsFields.type) &&
        Objects.equals(this.required, templatestemplateIdaddFieldsFields.required) &&
        Objects.equals(this.combValueOffset, templatestemplateIdaddFieldsFields.combValueOffset) &&
        Objects.equals(this.imageGravity, templatestemplateIdaddFieldsFields.imageGravity) &&
        Objects.equals(this.overflow, templatestemplateIdaddFieldsFields.overflow) &&
        Objects.equals(this.qrcodeColor, templatestemplateIdaddFieldsFields.qrcodeColor) &&
        Objects.equals(this.colorFieldRequired, templatestemplateIdaddFieldsFields.colorFieldRequired) &&
        Objects.equals(this.backgroundColorFieldRequired, templatestemplateIdaddFieldsFields.backgroundColorFieldRequired) &&
        Objects.equals(this.id, templatestemplateIdaddFieldsFields.id) &&
        Objects.equals(this.imageScaleType, templatestemplateIdaddFieldsFields.imageScaleType) &&
        Objects.equals(this.exclusiveMinimum, templatestemplateIdaddFieldsFields.exclusiveMinimum) &&
        Objects.equals(this.height, templatestemplateIdaddFieldsFields.height) &&
        Objects.equals(this.numberConditionRangeExclusiveMax, templatestemplateIdaddFieldsFields.numberConditionRangeExclusiveMax) &&
        Objects.equals(this.invertBooleanCondition, templatestemplateIdaddFieldsFields.invertBooleanCondition) &&
        Objects.equals(this.shapeFillColorFieldName, templatestemplateIdaddFieldsFields.shapeFillColorFieldName) &&
        Objects.equals(this._static, templatestemplateIdaddFieldsFields._static) &&
        Objects.equals(this.shapeBorderColorFieldName, templatestemplateIdaddFieldsFields.shapeBorderColorFieldName) &&
        Objects.equals(this.vAlignment, templatestemplateIdaddFieldsFields.vAlignment) &&
        Objects.equals(this.bold, templatestemplateIdaddFieldsFields.bold) &&
        Objects.equals(this.shapeBorderWidth, templatestemplateIdaddFieldsFields.shapeBorderWidth) &&
        Objects.equals(this.combNumberOfCells, templatestemplateIdaddFieldsFields.combNumberOfCells) &&
        Objects.equals(this.shapeBorderColor, templatestemplateIdaddFieldsFields.shapeBorderColor) &&
        Objects.equals(this.comb, templatestemplateIdaddFieldsFields.comb) &&
        Objects.equals(this.typeface, templatestemplateIdaddFieldsFields.typeface) &&
        Objects.equals(this.shapeType, templatestemplateIdaddFieldsFields.shapeType) &&
        Objects.equals(this.condition, templatestemplateIdaddFieldsFields.condition) &&
        Objects.equals(this.displayType, templatestemplateIdaddFieldsFields.displayType) &&
        Objects.equals(this.checkColor, templatestemplateIdaddFieldsFields.checkColor) &&
        Objects.equals(this.multilineLines, templatestemplateIdaddFieldsFields.multilineLines) &&
        Objects.equals(this.multiline, templatestemplateIdaddFieldsFields.multiline) &&
        Objects.equals(this.trueText, templatestemplateIdaddFieldsFields.trueText) &&
        Objects.equals(this.name, templatestemplateIdaddFieldsFields.name) &&
        Objects.equals(this.fontSize, templatestemplateIdaddFieldsFields.fontSize) &&
        Objects.equals(this.page, templatestemplateIdaddFieldsFields.page) &&
        Objects.equals(this.alignment, templatestemplateIdaddFieldsFields.alignment) &&
        Objects.equals(this.maxLength, templatestemplateIdaddFieldsFields.maxLength) &&
        Objects.equals(this.autoCalculateMaxLength, templatestemplateIdaddFieldsFields.autoCalculateMaxLength) &&
        Objects.equals(this.colorFieldName, templatestemplateIdaddFieldsFields.colorFieldName) &&
        Objects.equals(this.qrcodeColorFieldName, templatestemplateIdaddFieldsFields.qrcodeColorFieldName) &&
        Objects.equals(this.numberConditionRangeMin, templatestemplateIdaddFieldsFields.numberConditionRangeMin) &&
        Objects.equals(this.color, templatestemplateIdaddFieldsFields.color) &&
        Objects.equals(this.hidden, templatestemplateIdaddFieldsFields.hidden) &&
        Objects.equals(this.checkColorFieldRequired, templatestemplateIdaddFieldsFields.checkColorFieldRequired) &&
        Objects.equals(this.combinedFieldFormat, templatestemplateIdaddFieldsFields.combinedFieldFormat) &&
        Objects.equals(this.description, templatestemplateIdaddFieldsFields.description) &&
        Objects.equals(this.shapeBorderColorFieldRequired, templatestemplateIdaddFieldsFields.shapeBorderColorFieldRequired) &&
        Objects.equals(this.combinedFieldNames, templatestemplateIdaddFieldsFields.combinedFieldNames) &&
        Objects.equals(this.title, templatestemplateIdaddFieldsFields.title) &&
        Objects.equals(this.numberConditionRangeExclusiveMin, templatestemplateIdaddFieldsFields.numberConditionRangeExclusiveMin) &&
        Objects.equals(this.combinedFieldSeparator, templatestemplateIdaddFieldsFields.combinedFieldSeparator) &&
        Objects.equals(this.exclusiveMaximum, templatestemplateIdaddFieldsFields.exclusiveMaximum) &&
        Objects.equals(this._default, templatestemplateIdaddFieldsFields._default) &&
        Objects.equals(this.combinedFieldType, templatestemplateIdaddFieldsFields.combinedFieldType) &&
        Objects.equals(this.dateTimeFormat, templatestemplateIdaddFieldsFields.dateTimeFormat) &&
        Objects.equals(this.qrcodeColorFieldRequired, templatestemplateIdaddFieldsFields.qrcodeColorFieldRequired) &&
        Objects.equals(this.currency, templatestemplateIdaddFieldsFields.currency) &&
        Objects.equals(this.falseText, templatestemplateIdaddFieldsFields.falseText) &&
        Objects.equals(this.strikethrough, templatestemplateIdaddFieldsFields.strikethrough) &&
        Objects.equals(this.characterSpacing, templatestemplateIdaddFieldsFields.characterSpacing) &&
        Objects.equals(this.numberConditionRangeMax, templatestemplateIdaddFieldsFields.numberConditionRangeMax) &&
        Objects.equals(this.backgroundColor, templatestemplateIdaddFieldsFields.backgroundColor) &&
        Objects.equals(this.checkColorFieldName, templatestemplateIdaddFieldsFields.checkColorFieldName) &&
        Objects.equals(this.checkCharacter, templatestemplateIdaddFieldsFields.checkCharacter) &&
        Objects.equals(this.rotation, templatestemplateIdaddFieldsFields.rotation) &&
        Objects.equals(this.optionList, templatestemplateIdaddFieldsFields.optionList) &&
        Objects.equals(this.shapeFillColor, templatestemplateIdaddFieldsFields.shapeFillColor) &&
        Objects.equals(this.stringConditionType, templatestemplateIdaddFieldsFields.stringConditionType) &&
        Objects.equals(this.shapeFillColorFieldRequired, templatestemplateIdaddFieldsFields.shapeFillColorFieldRequired) &&
        Objects.equals(this.decimalPlaces, templatestemplateIdaddFieldsFields.decimalPlaces) &&
        Objects.equals(this.includeTime, templatestemplateIdaddFieldsFields.includeTime) &&
        Objects.equals(this.width, templatestemplateIdaddFieldsFields.width) &&
        Objects.equals(this.x, templatestemplateIdaddFieldsFields.x) &&
        Objects.equals(this.maximum, templatestemplateIdaddFieldsFields.maximum) &&
        Objects.equals(this.y, templatestemplateIdaddFieldsFields.y) &&
        Objects.equals(this.signatureAllowDraw, templatestemplateIdaddFieldsFields.signatureAllowDraw) &&
        Objects.equals(this.numberConditionType, templatestemplateIdaddFieldsFields.numberConditionType) &&
        Objects.equals(this.opacity, templatestemplateIdaddFieldsFields.opacity) &&
        Objects.equals(this.minimum, templatestemplateIdaddFieldsFields.minimum) &&
        Objects.equals(this.signatureAllowType, templatestemplateIdaddFieldsFields.signatureAllowType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundColorFieldName, uppercase, metadata, barcodeSymbology, minLength, integer, type, required, combValueOffset, imageGravity, overflow, qrcodeColor, colorFieldRequired, backgroundColorFieldRequired, id, imageScaleType, exclusiveMinimum, height, numberConditionRangeExclusiveMax, invertBooleanCondition, shapeFillColorFieldName, _static, shapeBorderColorFieldName, vAlignment, bold, shapeBorderWidth, combNumberOfCells, shapeBorderColor, comb, typeface, shapeType, condition, displayType, checkColor, multilineLines, multiline, trueText, name, fontSize, page, alignment, maxLength, autoCalculateMaxLength, colorFieldName, qrcodeColorFieldName, numberConditionRangeMin, color, hidden, checkColorFieldRequired, combinedFieldFormat, description, shapeBorderColorFieldRequired, combinedFieldNames, title, numberConditionRangeExclusiveMin, combinedFieldSeparator, exclusiveMaximum, _default, combinedFieldType, dateTimeFormat, qrcodeColorFieldRequired, currency, falseText, strikethrough, characterSpacing, numberConditionRangeMax, backgroundColor, checkColorFieldName, checkCharacter, rotation, optionList, shapeFillColor, stringConditionType, shapeFillColorFieldRequired, decimalPlaces, includeTime, width, x, maximum, y, signatureAllowDraw, numberConditionType, opacity, minimum, signatureAllowType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatestemplateIdaddFieldsFields {\n");
    
    sb.append("    backgroundColorFieldName: ").append(toIndentedString(backgroundColorFieldName)).append("\n");
    sb.append("    uppercase: ").append(toIndentedString(uppercase)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    barcodeSymbology: ").append(toIndentedString(barcodeSymbology)).append("\n");
    sb.append("    minLength: ").append(toIndentedString(minLength)).append("\n");
    sb.append("    integer: ").append(toIndentedString(integer)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    combValueOffset: ").append(toIndentedString(combValueOffset)).append("\n");
    sb.append("    imageGravity: ").append(toIndentedString(imageGravity)).append("\n");
    sb.append("    overflow: ").append(toIndentedString(overflow)).append("\n");
    sb.append("    qrcodeColor: ").append(toIndentedString(qrcodeColor)).append("\n");
    sb.append("    colorFieldRequired: ").append(toIndentedString(colorFieldRequired)).append("\n");
    sb.append("    backgroundColorFieldRequired: ").append(toIndentedString(backgroundColorFieldRequired)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageScaleType: ").append(toIndentedString(imageScaleType)).append("\n");
    sb.append("    exclusiveMinimum: ").append(toIndentedString(exclusiveMinimum)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    numberConditionRangeExclusiveMax: ").append(toIndentedString(numberConditionRangeExclusiveMax)).append("\n");
    sb.append("    invertBooleanCondition: ").append(toIndentedString(invertBooleanCondition)).append("\n");
    sb.append("    shapeFillColorFieldName: ").append(toIndentedString(shapeFillColorFieldName)).append("\n");
    sb.append("    _static: ").append(toIndentedString(_static)).append("\n");
    sb.append("    shapeBorderColorFieldName: ").append(toIndentedString(shapeBorderColorFieldName)).append("\n");
    sb.append("    vAlignment: ").append(toIndentedString(vAlignment)).append("\n");
    sb.append("    bold: ").append(toIndentedString(bold)).append("\n");
    sb.append("    shapeBorderWidth: ").append(toIndentedString(shapeBorderWidth)).append("\n");
    sb.append("    combNumberOfCells: ").append(toIndentedString(combNumberOfCells)).append("\n");
    sb.append("    shapeBorderColor: ").append(toIndentedString(shapeBorderColor)).append("\n");
    sb.append("    comb: ").append(toIndentedString(comb)).append("\n");
    sb.append("    typeface: ").append(toIndentedString(typeface)).append("\n");
    sb.append("    shapeType: ").append(toIndentedString(shapeType)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    displayType: ").append(toIndentedString(displayType)).append("\n");
    sb.append("    checkColor: ").append(toIndentedString(checkColor)).append("\n");
    sb.append("    multilineLines: ").append(toIndentedString(multilineLines)).append("\n");
    sb.append("    multiline: ").append(toIndentedString(multiline)).append("\n");
    sb.append("    trueText: ").append(toIndentedString(trueText)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    alignment: ").append(toIndentedString(alignment)).append("\n");
    sb.append("    maxLength: ").append(toIndentedString(maxLength)).append("\n");
    sb.append("    autoCalculateMaxLength: ").append(toIndentedString(autoCalculateMaxLength)).append("\n");
    sb.append("    colorFieldName: ").append(toIndentedString(colorFieldName)).append("\n");
    sb.append("    qrcodeColorFieldName: ").append(toIndentedString(qrcodeColorFieldName)).append("\n");
    sb.append("    numberConditionRangeMin: ").append(toIndentedString(numberConditionRangeMin)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    checkColorFieldRequired: ").append(toIndentedString(checkColorFieldRequired)).append("\n");
    sb.append("    combinedFieldFormat: ").append(toIndentedString(combinedFieldFormat)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    shapeBorderColorFieldRequired: ").append(toIndentedString(shapeBorderColorFieldRequired)).append("\n");
    sb.append("    combinedFieldNames: ").append(toIndentedString(combinedFieldNames)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    numberConditionRangeExclusiveMin: ").append(toIndentedString(numberConditionRangeExclusiveMin)).append("\n");
    sb.append("    combinedFieldSeparator: ").append(toIndentedString(combinedFieldSeparator)).append("\n");
    sb.append("    exclusiveMaximum: ").append(toIndentedString(exclusiveMaximum)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    combinedFieldType: ").append(toIndentedString(combinedFieldType)).append("\n");
    sb.append("    dateTimeFormat: ").append(toIndentedString(dateTimeFormat)).append("\n");
    sb.append("    qrcodeColorFieldRequired: ").append(toIndentedString(qrcodeColorFieldRequired)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    falseText: ").append(toIndentedString(falseText)).append("\n");
    sb.append("    strikethrough: ").append(toIndentedString(strikethrough)).append("\n");
    sb.append("    characterSpacing: ").append(toIndentedString(characterSpacing)).append("\n");
    sb.append("    numberConditionRangeMax: ").append(toIndentedString(numberConditionRangeMax)).append("\n");
    sb.append("    backgroundColor: ").append(toIndentedString(backgroundColor)).append("\n");
    sb.append("    checkColorFieldName: ").append(toIndentedString(checkColorFieldName)).append("\n");
    sb.append("    checkCharacter: ").append(toIndentedString(checkCharacter)).append("\n");
    sb.append("    rotation: ").append(toIndentedString(rotation)).append("\n");
    sb.append("    optionList: ").append(toIndentedString(optionList)).append("\n");
    sb.append("    shapeFillColor: ").append(toIndentedString(shapeFillColor)).append("\n");
    sb.append("    stringConditionType: ").append(toIndentedString(stringConditionType)).append("\n");
    sb.append("    shapeFillColorFieldRequired: ").append(toIndentedString(shapeFillColorFieldRequired)).append("\n");
    sb.append("    decimalPlaces: ").append(toIndentedString(decimalPlaces)).append("\n");
    sb.append("    includeTime: ").append(toIndentedString(includeTime)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    signatureAllowDraw: ").append(toIndentedString(signatureAllowDraw)).append("\n");
    sb.append("    numberConditionType: ").append(toIndentedString(numberConditionType)).append("\n");
    sb.append("    opacity: ").append(toIndentedString(opacity)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    signatureAllowType: ").append(toIndentedString(signatureAllowType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

